import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (36, 41, 58, 85, 98) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00500493, 0x000349b7, 0x10098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x2011ee93, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13, 0x0e003023, 0x0e003423]
def seg_25 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_32 : List (BitVec 32) := [0x6b502223, 0x6a000513, 0x04000593, 0x0f000613]
def seg_36 : List (BitVec 32) := [0x00000073]
def seg_37 : List (BitVec 32) := [0x00000b93]
def seg_38 : List (BitVec 32) := [0x001b8b93, 0x0d802223, 0x0c000513]
def seg_41 : List (BitVec 32) := [0x00000073]
def seg_42 : List (BitVec 32) := [0x001c0c13, 0x00700193, 0xfe3b94e3]
def seg_45 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0f003083, 0x0f803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xfa3a96e3]
def seg_54 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_58 : List (BitVec 32) := [0x00000073]
def seg_59 : List (BitVec 32) := [0x001a0a13, 0xf71a1ae3]
def seg_61 : List (BitVec 32) := [0x00100793]
def seg_62 : List (BitVec 32) := [0x02079193, 0x01041e93, 0x01d1e1b3, 0x3011e193, 0x1c303023, 0x1de02423, 0x0018d893, 0x00000813]
def seg_70 : List (BitVec 32) := [0x1d002623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x00398633]
def seg_85 : List (BitVec 32) := [0x00000073]
def seg_86 : List (BitVec 32) := [0x00180813, 0xfb181ee3]
def seg_88 : List (BitVec 32) := [0x00178793, 0xf8f4dae3]
def seg_90 : List (BitVec 32) := [0x000349b7, 0x10098993, 0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x00100293, 0x00000513]
def seg_98 : List (BitVec 32) := [0x00000073]

def L : Rv.Layout := [(0, seg_0), (25, seg_25), (32, seg_32), (36, seg_36), (37, seg_37), (38, seg_38), (41, seg_41), (42, seg_42), (45, seg_45), (54, seg_54), (58, seg_58), (59, seg_59), (61, seg_61), (62, seg_62), (70, seg_70), (85, seg_85), (86, seg_86), (88, seg_88), (90, seg_90), (98, seg_98)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 25)) seg_25 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_32 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) seg_32 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_36 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 36)) seg_36 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_37 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 37)) seg_37 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_38 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 38)) seg_38 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_41 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 41)) seg_41 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_42 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 42)) seg_42 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_45 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 45)) seg_45 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_54 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 54)) seg_54 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_58 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 58)) seg_58 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_59 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 59)) seg_59 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_61 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 61)) seg_61 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_62 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 62)) seg_62 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 70)) seg_70 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_85 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 85)) seg_85 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_86 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 86)) seg_86 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_88 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 88)) seg_88 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_90 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 90)) seg_90 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_98 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 98)) seg_98 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)

sym_block blk_0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 100
sym_block blk_25 := symRun { noAlias := true } seg_25 (BitVec.ofNat 64 (0x1000 + 4 * 25)) 100
sym_block blk_32 := symRun { noAlias := true } seg_32 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 100
sym_block blk_37 := symRun { noAlias := true } seg_37 (BitVec.ofNat 64 (0x1000 + 4 * 37)) 100
sym_block blk_38 := symRun { noAlias := true } seg_38 (BitVec.ofNat 64 (0x1000 + 4 * 38)) 100
sym_block blk_42 := symRun { noAlias := true } seg_42 (BitVec.ofNat 64 (0x1000 + 4 * 42)) 100
sym_block blk_45 := symRun { noAlias := true } seg_45 (BitVec.ofNat 64 (0x1000 + 4 * 45)) 100
sym_block blk_54 := symRun { noAlias := true } seg_54 (BitVec.ofNat 64 (0x1000 + 4 * 54)) 100
sym_block blk_59 := symRun { noAlias := true } seg_59 (BitVec.ofNat 64 (0x1000 + 4 * 59)) 100
sym_block blk_61 := symRun { noAlias := true } seg_61 (BitVec.ofNat 64 (0x1000 + 4 * 61)) 100
sym_block blk_62 := symRun { noAlias := true } seg_62 (BitVec.ofNat 64 (0x1000 + 4 * 62)) 100
sym_block blk_70 := symRun { noAlias := true } seg_70 (BitVec.ofNat 64 (0x1000 + 4 * 70)) 100
sym_block blk_86 := symRun { noAlias := true } seg_86 (BitVec.ofNat 64 (0x1000 + 4 * 86)) 100
sym_block blk_88 := symRun { noAlias := true } seg_88 (BitVec.ofNat 64 (0x1000 + 4 * 88)) 100
sym_block blk_90 := symRun { noAlias := true } seg_90 (BitVec.ofNat 64 (0x1000 + 4 * 90)) 100

end SigGolfCandidate.Keygen
