-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC0

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 1: instructions 1158 .. 1437, signature dwords 80 .. 159. -/

set_option maxRecDepth 100000

sym_block blk1158 := symRun { noAlias := true } seg1158 (pcOf 1158) 281

kernel_theorem blk1158_pc : ∀ t : MachineState, (blk1158.res.toState t).pc = pcOf 1438
kernel_theorem blk1158_addrs : ∀ t : MachineState, blk1158.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 80 + 8 * i))).reverse
kernel_theorem blk1158_words : ∀ t : MachineState,
    (blk1158.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 80)) 80 =
      ((packTab.drop 80).take 80).map (packDW t)

theorem packStep_1158 : PackStep 1158 1438 80 80 280 :=
  packStep_of blk1158 codeAt_1158 rfl blk1158_pc rfl rfl blk1158_words blk1158_addrs (by norm_num)

end SigGolfCandidate.Sign
