import SigGolfCandidate.Expand.Loop
import SigGolfCandidate.Submission

/-!
# `expand`: the program as 15 stages (prelude + copy loop) and a HALT block

Generated by `SigGolfCandidate/Expand/gen_expand.py` (segment table of `Images.expandCode`).
-/

namespace SigGolfCandidate.Expand
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv SigGolfCandidate.Mem

set_option maxRecDepth 8192

def pre0 : List (BitVec 32) := [0x00002337, 0x65030313, 0x000013b7, 0x80038393, 0x26c00413]
def pre1 : List (BitVec 32) := [0x00003337, 0x000023b7, 0x63038393, 0x00100413]
def pre2 : List (BitVec 32) := [0x00003337, 0x00430313, 0x000013b7, 0x1b038393, 0x0bc00413]
def pre3 : List (BitVec 32) := [0x00003337, 0x2f430313, 0x000023b7, 0x63438393, 0x00100413]
def pre4 : List (BitVec 32) := [0x00003337, 0x2f830313, 0x000013b7, 0x4a038393, 0x0bc00413]
def pre5 : List (BitVec 32) := [0x00003337, 0x5e830313, 0x000023b7, 0x63838393, 0x00100413]
def pre6 : List (BitVec 32) := [0x00003337, 0x5ec30313, 0x000013b7, 0x79038393, 0x0bc00413]
def pre7 : List (BitVec 32) := [0x00004337, 0x8dc30313, 0x000023b7, 0x63c38393, 0x00100413]
def pre8 : List (BitVec 32) := [0x00004337, 0x8e030313, 0x000023b7, 0xa8038393, 0x0bc00413]
def pre9 : List (BitVec 32) := [0x00004337, 0xbd030313, 0x000023b7, 0x64038393, 0x00100413]
def pre10 : List (BitVec 32) := [0x00004337, 0xbd430313, 0x000023b7, 0xd7038393, 0x0bc00413]
def pre11 : List (BitVec 32) := [0x00004337, 0xec430313, 0x000023b7, 0x64438393, 0x00100413]
def pre12 : List (BitVec 32) := [0x00004337, 0xec830313, 0x000023b7, 0x06038393, 0x0bc00413]
def pre13 : List (BitVec 32) := [0x00004337, 0x1b830313, 0x000023b7, 0x64838393, 0x00100413]
def pre14 : List (BitVec 32) := [0x00004337, 0x1bc30313, 0x000023b7, 0x35038393, 0x0b800413]
def fin : List (BitVec 32) := [0x00100293, 0x00000513, 0x00000073]

/-- Segment table. -/
def L : Rv.Layout := [(0, pre0), (5, loopCode), (11, pre1), (15, loopCode), (21, pre2), (26, loopCode), (32, pre3), (37, loopCode), (43, pre4), (48, loopCode), (54, pre5), (59, loopCode), (65, pre6), (70, loopCode), (76, pre7), (81, loopCode), (87, pre8), (92, loopCode), (98, pre9), (103, loopCode), (109, pre10), (114, loopCode), (120, pre11), (125, loopCode), (131, pre12), (136, loopCode), (142, pre13), (147, loopCode), (153, pre14), (158, loopCode), (164, fin)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The expand image. -/
abbrev image : Image := submission.image .expand

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) pre0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_1 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 5)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_2 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 11)) pre1 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_3 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 15)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_4 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 21)) pre2 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_5 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 26)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_6 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) pre3 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_7 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 37)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_8 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 43)) pre4 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_9 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 48)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_10 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 54)) pre5 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_11 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 59)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_12 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 65)) pre6 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_13 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 70)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_14 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 76)) pre7 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_15 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 81)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_16 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 87)) pre8 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_17 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 92)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_18 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 98)) pre9 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_19 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 103)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_20 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 109)) pre10 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_21 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 114)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_22 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 120)) pre11 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_23 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 125)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_24 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 131)) pre12 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 136)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_26 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 142)) pre13 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_27 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 147)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_28 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 153)) pre14 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_29 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 158)) loopCode :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_30 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 164)) fin :=
  codeAt_layout code_eq layout_ok (i := 30) (by kernel_rfl) (by decide)

sym_block run0 := symRun {} pre0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 10
sym_block run1 := symRun {} pre1 (BitVec.ofNat 64 (0x1000 + 4 * 11)) 10
sym_block run2 := symRun {} pre2 (BitVec.ofNat 64 (0x1000 + 4 * 21)) 10
sym_block run3 := symRun {} pre3 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 10
sym_block run4 := symRun {} pre4 (BitVec.ofNat 64 (0x1000 + 4 * 43)) 10
sym_block run5 := symRun {} pre5 (BitVec.ofNat 64 (0x1000 + 4 * 54)) 10
sym_block run6 := symRun {} pre6 (BitVec.ofNat 64 (0x1000 + 4 * 65)) 10
sym_block run7 := symRun {} pre7 (BitVec.ofNat 64 (0x1000 + 4 * 76)) 10
sym_block run8 := symRun {} pre8 (BitVec.ofNat 64 (0x1000 + 4 * 87)) 10
sym_block run9 := symRun {} pre9 (BitVec.ofNat 64 (0x1000 + 4 * 98)) 10
sym_block run10 := symRun {} pre10 (BitVec.ofNat 64 (0x1000 + 4 * 109)) 10
sym_block run11 := symRun {} pre11 (BitVec.ofNat 64 (0x1000 + 4 * 120)) 10
sym_block run12 := symRun {} pre12 (BitVec.ofNat 64 (0x1000 + 4 * 131)) 10
sym_block run13 := symRun {} pre13 (BitVec.ofNat 64 (0x1000 + 4 * 142)) 10
sym_block run14 := symRun {} pre14 (BitVec.ofNat 64 (0x1000 + 4 * 153)) 10
sym_block runFin := symRun {} fin (BitVec.ofNat 64 (0x1000 + 4 * 164)) 10

/-- The fifteen copies `(src, dst, words)` in program order. -/
def copies : List (Nat × Nat × Nat) := [(9808, 2048, 620), (12288, 9776, 1), (12292, 4528, 188), (13044, 9780, 1), (13048, 5280, 188), (13800, 9784, 1), (13804, 6032, 188), (14556, 9788, 1), (14560, 6784, 188), (15312, 9792, 1), (15316, 7536, 188), (16068, 9796, 1), (16072, 8288, 188), (16824, 9800, 1), (16828, 9040, 184)]

theorem stage0 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 0))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run0.res.steps + 620 * 6) (run0.res.cycles + 620 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 5) + 24 ∧ BytesEq u (applyCopy (9808, 2048, 620) f) :=
  stage run0 codeAt_0 rfl rfl rfl rfl rfl rfl codeAt_1 (by decide) t htpc f hf

theorem stage1 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 11))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run1.res.steps + 1 * 6) (run1.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 15) + 24 ∧ BytesEq u (applyCopy (12288, 9776, 1) f) :=
  stage run1 codeAt_2 rfl rfl rfl rfl rfl rfl codeAt_3 (by decide) t htpc f hf

theorem stage2 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 21))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run2.res.steps + 188 * 6) (run2.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 26) + 24 ∧ BytesEq u (applyCopy (12292, 4528, 188) f) :=
  stage run2 codeAt_4 rfl rfl rfl rfl rfl rfl codeAt_5 (by decide) t htpc f hf

theorem stage3 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 32))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run3.res.steps + 1 * 6) (run3.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 37) + 24 ∧ BytesEq u (applyCopy (13044, 9780, 1) f) :=
  stage run3 codeAt_6 rfl rfl rfl rfl rfl rfl codeAt_7 (by decide) t htpc f hf

theorem stage4 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 43))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run4.res.steps + 188 * 6) (run4.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 48) + 24 ∧ BytesEq u (applyCopy (13048, 5280, 188) f) :=
  stage run4 codeAt_8 rfl rfl rfl rfl rfl rfl codeAt_9 (by decide) t htpc f hf

theorem stage5 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 54))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run5.res.steps + 1 * 6) (run5.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 59) + 24 ∧ BytesEq u (applyCopy (13800, 9784, 1) f) :=
  stage run5 codeAt_10 rfl rfl rfl rfl rfl rfl codeAt_11 (by decide) t htpc f hf

theorem stage6 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 65))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run6.res.steps + 188 * 6) (run6.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 70) + 24 ∧ BytesEq u (applyCopy (13804, 6032, 188) f) :=
  stage run6 codeAt_12 rfl rfl rfl rfl rfl rfl codeAt_13 (by decide) t htpc f hf

theorem stage7 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 76))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run7.res.steps + 1 * 6) (run7.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 81) + 24 ∧ BytesEq u (applyCopy (14556, 9788, 1) f) :=
  stage run7 codeAt_14 rfl rfl rfl rfl rfl rfl codeAt_15 (by decide) t htpc f hf

theorem stage8 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 87))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run8.res.steps + 188 * 6) (run8.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 92) + 24 ∧ BytesEq u (applyCopy (14560, 6784, 188) f) :=
  stage run8 codeAt_16 rfl rfl rfl rfl rfl rfl codeAt_17 (by decide) t htpc f hf

theorem stage9 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 98))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run9.res.steps + 1 * 6) (run9.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 103) + 24 ∧ BytesEq u (applyCopy (15312, 9792, 1) f) :=
  stage run9 codeAt_18 rfl rfl rfl rfl rfl rfl codeAt_19 (by decide) t htpc f hf

theorem stage10 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 109))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run10.res.steps + 188 * 6) (run10.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 114) + 24 ∧ BytesEq u (applyCopy (15316, 7536, 188) f) :=
  stage run10 codeAt_20 rfl rfl rfl rfl rfl rfl codeAt_21 (by decide) t htpc f hf

theorem stage11 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 120))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run11.res.steps + 1 * 6) (run11.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 125) + 24 ∧ BytesEq u (applyCopy (16068, 9796, 1) f) :=
  stage run11 codeAt_22 rfl rfl rfl rfl rfl rfl codeAt_23 (by decide) t htpc f hf

theorem stage12 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 131))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run12.res.steps + 188 * 6) (run12.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 136) + 24 ∧ BytesEq u (applyCopy (16072, 8288, 188) f) :=
  stage run12 codeAt_24 rfl rfl rfl rfl rfl rfl codeAt_25 (by decide) t htpc f hf

theorem stage13 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 142))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run13.res.steps + 1 * 6) (run13.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 147) + 24 ∧ BytesEq u (applyCopy (16824, 9800, 1) f) :=
  stage run13 codeAt_26 rfl rfl rfl rfl rfl rfl codeAt_27 (by decide) t htpc f hf

theorem stage14 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 153))
    (f : Nat → Byte) (hf : BytesEq t f) :
    ∃ u, Steps image t (run14.res.steps + 184 * 6) (run14.res.cycles + 184 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 158) + 24 ∧ BytesEq u (applyCopy (16828, 9040, 184) f) :=
  stage run14 codeAt_28 rfl rfl rfl rfl rfl rfl codeAt_29 (by decide) t htpc f hf


end SigGolfCandidate.Expand
