-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC0

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 1: instructions 1050 .. 1294, signature dwords 80 .. 159. -/

set_option maxRecDepth 100000

sym_block blk1050 := symRun { noAlias := true } seg1050 (pcOf 1050) 246

kernel_theorem blk1050_pc : ∀ t : MachineState, (blk1050.res.toState t).pc = pcOf 1295
kernel_theorem blk1050_addrs : ∀ t : MachineState, blk1050.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 80 + 8 * i))).reverse
kernel_theorem blk1050_words : ∀ t : MachineState,
    (blk1050.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 80)) 80 =
      ((packTab.drop 80).take 80).map (packDW t)

theorem packStep_1050 : PackStep 1050 1295 80 80 245 :=
  packStep_of blk1050 codeAt_1050 rfl blk1050_pc rfl rfl blk1050_words blk1050_addrs (by norm_num)

end SigGolfCandidate.Sign
