-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC4

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 5: instructions 2246 .. 2664, signature dwords 400 .. 479. -/

set_option maxRecDepth 100000

sym_block blk2246 := symRun { noAlias := true } seg2246 (pcOf 2246) 420

kernel_theorem blk2246_pc : ∀ t : MachineState, (blk2246.res.toState t).pc = pcOf 2665
kernel_theorem blk2246_addrs : ∀ t : MachineState, blk2246.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 400 + 8 * i))).reverse
kernel_theorem blk2246_words : ∀ t : MachineState,
    (blk2246.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 400)) 80 =
      ((packTab.drop 400).take 80).map (packDW t)

theorem packStep_2246 : PackStep 2246 2665 400 80 419 :=
  packStep_of blk2246 codeAt_2246 rfl blk2246_pc rfl rfl blk2246_words blk2246_addrs (by norm_num)

end SigGolfCandidate.Sign
