-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.Code

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the sign program (before the pack). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 56
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 3
sym_block blk59 := symRun { noAlias := true } seg59 (pcOf 59) 3
sym_block blk61 := symRun { noAlias := true } seg61 (pcOf 61) 3
sym_block blk63 := symRun { noAlias := true } seg63 (pcOf 63) 3
sym_block blk65 := symRun { noAlias := true } seg65 (pcOf 65) 6
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 9
sym_block blk78 := symRun { noAlias := true } seg78 (pcOf 78) 5
sym_block blk82 := symRun { noAlias := true } seg82 (pcOf 82) 3
sym_block blk84 := symRun { noAlias := true } seg84 (pcOf 84) 4
sym_block blk87 := symRun { noAlias := true } seg87 (pcOf 87) 4
sym_block blk90 := symRun { noAlias := true } seg90 (pcOf 90) 67
sym_block blk156 := symRun { noAlias := true } seg156 (pcOf 156) 9
sym_block blk164 := symRun { noAlias := true } seg164 (pcOf 164) 3
sym_block blk166 := symRun { noAlias := true } seg166 (pcOf 166) 7
sym_block blk172 := symRun { noAlias := true } seg172 (pcOf 172) 8
sym_block blk179 := symRun { noAlias := true } seg179 (pcOf 179) 5
sym_block blk183 := symRun { noAlias := true } seg183 (pcOf 183) 6
sym_block blk188 := symRun { noAlias := true } seg188 (pcOf 188) 4
sym_block blk191 := symRun { noAlias := true } seg191 (pcOf 191) 3
sym_block blk193 := symRun { noAlias := true } seg193 (pcOf 193) 18
sym_block blk210 := symRun { noAlias := true } seg210 (pcOf 210) 18
sym_block blk227 := symRun { noAlias := true } seg227 (pcOf 227) 3
sym_block blk229 := symRun { noAlias := true } seg229 (pcOf 229) 4
sym_block blk232 := symRun { noAlias := true } seg232 (pcOf 232) 10
sym_block blk241 := symRun { noAlias := true } seg241 (pcOf 241) 12
sym_block blk252 := symRun { noAlias := true } seg252 (pcOf 252) 21
sym_block blk272 := symRun { noAlias := true } seg272 (pcOf 272) 3
sym_block blk274 := symRun { noAlias := true } seg274 (pcOf 274) 4
sym_block blk277 := symRun { noAlias := true } seg277 (pcOf 277) 2
sym_block blk278 := symRun { noAlias := true } seg278 (pcOf 278) 8
sym_block blk285 := symRun { noAlias := true } seg285 (pcOf 285) 3
sym_block blk287 := symRun { noAlias := true } seg287 (pcOf 287) 16
sym_block blk302 := symRun { noAlias := true } seg302 (pcOf 302) 6
sym_block blk307 := symRun { noAlias := true } seg307 (pcOf 307) 5
sym_block blk311 := symRun { noAlias := true } seg311 (pcOf 311) 22
sym_block blk332 := symRun { noAlias := true } seg332 (pcOf 332) 2
sym_block blk333 := symRun { noAlias := true } seg333 (pcOf 333) 3
sym_block blk335 := symRun { noAlias := true } seg335 (pcOf 335) 4
sym_block blk338 := symRun { noAlias := true } seg338 (pcOf 338) 128
sym_block blk465 := symRun { noAlias := true } seg465 (pcOf 465) 15
sym_block blk479 := symRun { noAlias := true } seg479 (pcOf 479) 8
sym_block blk486 := symRun { noAlias := true } seg486 (pcOf 486) 3
sym_block blk488 := symRun { noAlias := true } seg488 (pcOf 488) 7
sym_block blk494 := symRun { noAlias := true } seg494 (pcOf 494) 13
sym_block blk506 := symRun { noAlias := true } seg506 (pcOf 506) 2
sym_block blk507 := symRun { noAlias := true } seg507 (pcOf 507) 7
sym_block blk513 := symRun { noAlias := true } seg513 (pcOf 513) 9
sym_block blk521 := symRun { noAlias := true } seg521 (pcOf 521) 3
sym_block blk523 := symRun { noAlias := true } seg523 (pcOf 523) 2
sym_block blk524 := symRun { noAlias := true } seg524 (pcOf 524) 7
sym_block blk530 := symRun { noAlias := true } seg530 (pcOf 530) 3
sym_block blk532 := symRun { noAlias := true } seg532 (pcOf 532) 10
sym_block blk541 := symRun { noAlias := true } seg541 (pcOf 541) 6
sym_block blk546 := symRun { noAlias := true } seg546 (pcOf 546) 3
sym_block blk548 := symRun { noAlias := true } seg548 (pcOf 548) 2
sym_block blk549 := symRun { noAlias := true } seg549 (pcOf 549) 18
sym_block blk566 := symRun { noAlias := true } seg566 (pcOf 566) 18
sym_block blk583 := symRun { noAlias := true } seg583 (pcOf 583) 3
sym_block blk585 := symRun { noAlias := true } seg585 (pcOf 585) 3
sym_block blk587 := symRun { noAlias := true } seg587 (pcOf 587) 8
sym_block blk594 := symRun { noAlias := true } seg594 (pcOf 594) 10
sym_block blk603 := symRun { noAlias := true } seg603 (pcOf 603) 3
sym_block blk605 := symRun { noAlias := true } seg605 (pcOf 605) 7
sym_block blk611 := symRun { noAlias := true } seg611 (pcOf 611) 12
sym_block blk622 := symRun { noAlias := true } seg622 (pcOf 622) 2
sym_block blk623 := symRun { noAlias := true } seg623 (pcOf 623) 8
sym_block blk630 := symRun { noAlias := true } seg630 (pcOf 630) 4
sym_block blk633 := symRun { noAlias := true } seg633 (pcOf 633) 10
sym_block blk642 := symRun { noAlias := true } seg642 (pcOf 642) 5
sym_block blk646 := symRun { noAlias := true } seg646 (pcOf 646) 13
sym_block blk658 := symRun { noAlias := true } seg658 (pcOf 658) 18

end SigGolfCandidate.Sign
