import SigGolfCandidate.Expand.Stages

/-!
# `expand`: composition of the stages (generated by `SigGolfCandidate/Expand/gen_expand.py`)
-/

namespace SigGolfCandidate.Expand
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv SigGolfCandidate.Mem

/-- The whole program up to the final `ecall`: 11710 steps and cycles, `t0 = 1`, `a0 = 0`, and
the byte view of memory is the fifteen copies applied to the initial one. -/
theorem expand_steps (s : MachineState) (hpc : s.pc = 0x1000) :
    ∃ u, Steps image s 11710 11710 u ∧ fetch image u = some (.base .ECALL) ∧
      u.getReg .x5 = 1 ∧ u.getReg .x10 = 0 ∧
      BytesEq u (applyCopies copies (fun a => s.getByte (BitVec.ofNat 64 a))) := by
  obtain ⟨u0, st0, pc0, b0⟩ := stage0 s (by rw [hpc]; rfl) _ (fun a _ => rfl)
  obtain ⟨u1, st1, pc1, b1⟩ := stage1 u0 (by rw [pc0]; decide) _ b0
  obtain ⟨u2, st2, pc2, b2⟩ := stage2 u1 (by rw [pc1]; decide) _ b1
  obtain ⟨u3, st3, pc3, b3⟩ := stage3 u2 (by rw [pc2]; decide) _ b2
  obtain ⟨u4, st4, pc4, b4⟩ := stage4 u3 (by rw [pc3]; decide) _ b3
  obtain ⟨u5, st5, pc5, b5⟩ := stage5 u4 (by rw [pc4]; decide) _ b4
  obtain ⟨u6, st6, pc6, b6⟩ := stage6 u5 (by rw [pc5]; decide) _ b5
  obtain ⟨u7, st7, pc7, b7⟩ := stage7 u6 (by rw [pc6]; decide) _ b6
  obtain ⟨u8, st8, pc8, b8⟩ := stage8 u7 (by rw [pc7]; decide) _ b7
  obtain ⟨u9, st9, pc9, b9⟩ := stage9 u8 (by rw [pc8]; decide) _ b8
  obtain ⟨u10, st10, pc10, b10⟩ := stage10 u9 (by rw [pc9]; decide) _ b9
  obtain ⟨u11, st11, pc11, b11⟩ := stage11 u10 (by rw [pc10]; decide) _ b10
  obtain ⟨u12, st12, pc12, b12⟩ := stage12 u11 (by rw [pc11]; decide) _ b11
  obtain ⟨u13, st13, pc13, b13⟩ := stage13 u12 (by rw [pc12]; decide) _ b12
  obtain ⟨u14, st14, pc14, b14⟩ := stage14 u13 (by rw [pc13]; decide) _ b13
  have hpcF : u14.pc = BitVec.ofNat 64 (0x1000 + 4 * 164) := by rw [pc14]; decide
  have hobl : runFin.res.obligs u14 := by simp only [runFin.res, rv_simp]
  have stF := symRun_sound runFin codeAt_30 u14 hpcF hobl
  refine ⟨_, Steps.of_eq (((((((((((((((st0.trans st1).trans st2).trans st3).trans st4).trans st5).trans st6).trans st7).trans st8).trans st9).trans st10).trans st11).trans st12).trans st13).trans st14).trans stF) rfl rfl,
    symRun_ecall runFin codeAt_30 u14 hobl rfl, by simp [runFin.res, rv_simp], by simp [runFin.res, rv_simp], ?_⟩
  intro a ha
  have h := b14 a ha
  simp only [MachineState.getByte, Result.toState_getMem, runFin.res, memEval_nil] at h ⊢
  exact h

/-- Every witness byte is the destination of exactly the copy that reads its `witnessSrc`. -/
theorem copies_cover (i : Nat) (hi : i < 7756) :
    ∃ c ∈ copies, c.2.1 ≤ 0x800 + i ∧ 0x800 + i < c.2.1 + 4 * c.2.2 ∧
      0x800 + i - c.2.1 + c.1 = 0x2650 + Ref.witnessSrc i := by
  unfold Ref.witnessSrc Ref.sigLayerOff Ref.witLayerOff Ref.witCounters
  rcases (show i < 2480 ∨ (2480 + 752 * 0 ≤ i ∧ i < 2480 + 752 * 0 + 4 * 188) ∨ (7728 + 4 * 0 ≤ i ∧ i < 7728 + 4 * 0 + 4) ∨ (2480 + 752 * 1 ≤ i ∧ i < 2480 + 752 * 1 + 4 * 188) ∨ (7728 + 4 * 1 ≤ i ∧ i < 7728 + 4 * 1 + 4) ∨ (2480 + 752 * 2 ≤ i ∧ i < 2480 + 752 * 2 + 4 * 188) ∨ (7728 + 4 * 2 ≤ i ∧ i < 7728 + 4 * 2 + 4) ∨ (2480 + 752 * 3 ≤ i ∧ i < 2480 + 752 * 3 + 4 * 188) ∨ (7728 + 4 * 3 ≤ i ∧ i < 7728 + 4 * 3 + 4) ∨ (2480 + 752 * 4 ≤ i ∧ i < 2480 + 752 * 4 + 4 * 188) ∨ (7728 + 4 * 4 ≤ i ∧ i < 7728 + 4 * 4 + 4) ∨ (2480 + 752 * 5 ≤ i ∧ i < 2480 + 752 * 5 + 4 * 188) ∨ (7728 + 4 * 5 ≤ i ∧ i < 7728 + 4 * 5 + 4) ∨ (2480 + 752 * 6 ≤ i ∧ i < 2480 + 752 * 6 + 4 * 184) ∨ (7728 + 4 * 6 ≤ i ∧ i < 7728 + 4 * 6 + 4) by omega) with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
  · refine ⟨(9808, 2048, 620), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(12292, 4528, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(12288, 9776, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(13048, 5280, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(13044, 9780, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(13804, 6032, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(13800, 9784, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(14560, 6784, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(14556, 9788, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(15316, 7536, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(15312, 9792, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(16072, 8288, 188), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(16068, 9796, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(16828, 9040, 184), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega
  · refine ⟨(16824, 9800, 1), by simp [copies], ?_, ?_, ?_⟩ <;> dsimp only <;> (try split_ifs) <;> omega

end SigGolfCandidate.Expand
