import SigGolfCandidate.Expand.Stages

/-!
# `expand`: composition of the stages (generated by `SigGolfCandidate/Expand/gen_expand.py`)
-/

namespace SigGolfCandidate.Expand
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv SigGolfCandidate.Mem

/-- The whole program up to the final `ecall`: 9662 steps and cycles, `t0 = 1`, `a0 = 0`, and
the byte view of memory is the copies applied to the initial one. -/
theorem expand_steps (s : MachineState) (hpc : s.pc = 0x1000) :
    ∃ u, Steps image s 9662 9662 u ∧ fetch image u = some (.base .ECALL) ∧
      u.getReg .x5 = 1 ∧ u.getReg .x10 = 0 ∧
      BytesEq u (applyCopies copies (fun a => s.getByte (BitVec.ofNat 64 a))) := by
  obtain ⟨u0, st0, pc0, b0⟩ := stage0 s (by rw [hpc]; rfl) _ (fun a _ => rfl)
  obtain ⟨u1, st1, pc1, b1⟩ := stage1 u0 (by rw [pc0]; decide) _ b0
  obtain ⟨u2, st2, pc2, b2⟩ := stage2 u1 (by rw [pc1]; decide) _ b1
  obtain ⟨u3, st3, pc3, b3⟩ := stage3 u2 (by rw [pc2]; decide) _ b2
  obtain ⟨u4, st4, pc4, b4⟩ := stage4 u3 (by rw [pc3]; decide) _ b3
  obtain ⟨u5, st5, pc5, b5⟩ := stage5 u4 (by rw [pc4]; decide) _ b4
  obtain ⟨u6, st6, pc6, b6⟩ := stage6 u5 (by rw [pc5]; decide) _ b5
  obtain ⟨u7, st7, pc7, b7⟩ := stage7 u6 (by rw [pc6]; decide) _ b6
  obtain ⟨u8, st8, pc8, b8⟩ := stage8 u7 (by rw [pc7]; decide) _ b7
  obtain ⟨u9, st9, pc9, b9⟩ := stage9 u8 (by rw [pc8]; decide) _ b8
  obtain ⟨u10, st10, pc10, b10⟩ := stage10 u9 (by rw [pc9]; decide) _ b9
  have hpcF : u10.pc = BitVec.ofNat 64 (0x1000 + 4 * 120) := by rw [pc10]; decide
  have hobl : runFin.res.obligs u10 := by simp only [runFin.res, rv_simp]
  have stF := symRun_sound runFin codeAt_22 u10 hpcF hobl
  refine ⟨_, Steps.of_eq (((((((((((st0.trans st1).trans st2).trans st3).trans st4).trans st5).trans st6).trans st7).trans st8).trans st9).trans st10).trans stF) rfl rfl,
    symRun_ecall runFin codeAt_22 u10 hobl rfl, by simp [runFin.res, rv_simp], by simp [runFin.res, rv_simp], ?_⟩
  intro a ha
  have h := b10 a ha
  simp only [MachineState.getByte, Result.toState_getMem, runFin.res, memEval_nil] at h ⊢
  exact h

end SigGolfCandidate.Expand
