-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC1

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 2: instructions 1438 .. 1748, signature dwords 160 .. 239. -/

set_option maxRecDepth 100000

sym_block blk1438 := symRun { noAlias := true } seg1438 (pcOf 1438) 312

kernel_theorem blk1438_pc : ∀ t : MachineState, (blk1438.res.toState t).pc = pcOf 1749
kernel_theorem blk1438_addrs : ∀ t : MachineState, blk1438.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 160 + 8 * i))).reverse
kernel_theorem blk1438_words : ∀ t : MachineState,
    (blk1438.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 160)) 80 =
      ((packTab.drop 160).take 80).map (packDW t)

theorem packStep_1438 : PackStep 1438 1749 160 80 311 :=
  packStep_of blk1438 codeAt_1438 rfl blk1438_pc rfl rfl blk1438_words blk1438_addrs (by norm_num)

end SigGolfCandidate.Sign
