-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.Code

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the sign program (before the pack). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 56
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 3
sym_block blk59 := symRun { noAlias := true } seg59 (pcOf 59) 3
sym_block blk61 := symRun { noAlias := true } seg61 (pcOf 61) 3
sym_block blk63 := symRun { noAlias := true } seg63 (pcOf 63) 3
sym_block blk65 := symRun { noAlias := true } seg65 (pcOf 65) 6
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 6
sym_block blk75 := symRun { noAlias := true } seg75 (pcOf 75) 5
sym_block blk79 := symRun { noAlias := true } seg79 (pcOf 79) 3
sym_block blk81 := symRun { noAlias := true } seg81 (pcOf 81) 4
sym_block blk84 := symRun { noAlias := true } seg84 (pcOf 84) 4
sym_block blk87 := symRun { noAlias := true } seg87 (pcOf 87) 67
sym_block blk153 := symRun { noAlias := true } seg153 (pcOf 153) 9
sym_block blk161 := symRun { noAlias := true } seg161 (pcOf 161) 3
sym_block blk163 := symRun { noAlias := true } seg163 (pcOf 163) 7
sym_block blk169 := symRun { noAlias := true } seg169 (pcOf 169) 8
sym_block blk176 := symRun { noAlias := true } seg176 (pcOf 176) 5
sym_block blk180 := symRun { noAlias := true } seg180 (pcOf 180) 6
sym_block blk185 := symRun { noAlias := true } seg185 (pcOf 185) 4
sym_block blk188 := symRun { noAlias := true } seg188 (pcOf 188) 3
sym_block blk190 := symRun { noAlias := true } seg190 (pcOf 190) 20
sym_block blk209 := symRun { noAlias := true } seg209 (pcOf 209) 17
sym_block blk225 := symRun { noAlias := true } seg225 (pcOf 225) 3
sym_block blk227 := symRun { noAlias := true } seg227 (pcOf 227) 4
sym_block blk230 := symRun { noAlias := true } seg230 (pcOf 230) 10
sym_block blk239 := symRun { noAlias := true } seg239 (pcOf 239) 12
sym_block blk250 := symRun { noAlias := true } seg250 (pcOf 250) 21
sym_block blk270 := symRun { noAlias := true } seg270 (pcOf 270) 3
sym_block blk272 := symRun { noAlias := true } seg272 (pcOf 272) 4
sym_block blk275 := symRun { noAlias := true } seg275 (pcOf 275) 2
sym_block blk276 := symRun { noAlias := true } seg276 (pcOf 276) 8
sym_block blk283 := symRun { noAlias := true } seg283 (pcOf 283) 3
sym_block blk285 := symRun { noAlias := true } seg285 (pcOf 285) 16
sym_block blk300 := symRun { noAlias := true } seg300 (pcOf 300) 6
sym_block blk305 := symRun { noAlias := true } seg305 (pcOf 305) 5
sym_block blk309 := symRun { noAlias := true } seg309 (pcOf 309) 22
sym_block blk330 := symRun { noAlias := true } seg330 (pcOf 330) 2
sym_block blk331 := symRun { noAlias := true } seg331 (pcOf 331) 3
sym_block blk333 := symRun { noAlias := true } seg333 (pcOf 333) 4
sym_block blk336 := symRun { noAlias := true } seg336 (pcOf 336) 128
sym_block blk463 := symRun { noAlias := true } seg463 (pcOf 463) 15
sym_block blk477 := symRun { noAlias := true } seg477 (pcOf 477) 8
sym_block blk484 := symRun { noAlias := true } seg484 (pcOf 484) 3
sym_block blk486 := symRun { noAlias := true } seg486 (pcOf 486) 7
sym_block blk492 := symRun { noAlias := true } seg492 (pcOf 492) 13
sym_block blk504 := symRun { noAlias := true } seg504 (pcOf 504) 2
sym_block blk505 := symRun { noAlias := true } seg505 (pcOf 505) 7
sym_block blk511 := symRun { noAlias := true } seg511 (pcOf 511) 5
sym_block blk515 := symRun { noAlias := true } seg515 (pcOf 515) 3
sym_block blk517 := symRun { noAlias := true } seg517 (pcOf 517) 2
sym_block blk518 := symRun { noAlias := true } seg518 (pcOf 518) 7
sym_block blk524 := symRun { noAlias := true } seg524 (pcOf 524) 3
sym_block blk526 := symRun { noAlias := true } seg526 (pcOf 526) 10
sym_block blk535 := symRun { noAlias := true } seg535 (pcOf 535) 6
sym_block blk540 := symRun { noAlias := true } seg540 (pcOf 540) 3
sym_block blk542 := symRun { noAlias := true } seg542 (pcOf 542) 2
sym_block blk543 := symRun { noAlias := true } seg543 (pcOf 543) 20
sym_block blk562 := symRun { noAlias := true } seg562 (pcOf 562) 17
sym_block blk578 := symRun { noAlias := true } seg578 (pcOf 578) 3
sym_block blk580 := symRun { noAlias := true } seg580 (pcOf 580) 3
sym_block blk582 := symRun { noAlias := true } seg582 (pcOf 582) 8
sym_block blk589 := symRun { noAlias := true } seg589 (pcOf 589) 10
sym_block blk598 := symRun { noAlias := true } seg598 (pcOf 598) 3
sym_block blk600 := symRun { noAlias := true } seg600 (pcOf 600) 7
sym_block blk606 := symRun { noAlias := true } seg606 (pcOf 606) 12
sym_block blk617 := symRun { noAlias := true } seg617 (pcOf 617) 2
sym_block blk618 := symRun { noAlias := true } seg618 (pcOf 618) 4
sym_block blk621 := symRun { noAlias := true } seg621 (pcOf 621) 4
sym_block blk624 := symRun { noAlias := true } seg624 (pcOf 624) 10
sym_block blk633 := symRun { noAlias := true } seg633 (pcOf 633) 5
sym_block blk637 := symRun { noAlias := true } seg637 (pcOf 637) 13
sym_block blk649 := symRun { noAlias := true } seg649 (pcOf 649) 18

end SigGolfCandidate.Sign
