-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.Code

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the sign program (before the pack). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 56
sym_block blk55 := symRun { noAlias := true } seg55 (pcOf 55) 3
sym_block blk57 := symRun { noAlias := true } seg57 (pcOf 57) 3
sym_block blk59 := symRun { noAlias := true } seg59 (pcOf 59) 3
sym_block blk61 := symRun { noAlias := true } seg61 (pcOf 61) 3
sym_block blk63 := symRun { noAlias := true } seg63 (pcOf 63) 3
sym_block blk65 := symRun { noAlias := true } seg65 (pcOf 65) 6
sym_block blk70 := symRun { noAlias := true } seg70 (pcOf 70) 6
sym_block blk75 := symRun { noAlias := true } seg75 (pcOf 75) 5
sym_block blk79 := symRun { noAlias := true } seg79 (pcOf 79) 3
sym_block blk81 := symRun { noAlias := true } seg81 (pcOf 81) 4
sym_block blk84 := symRun { noAlias := true } seg84 (pcOf 84) 4
sym_block blk87 := symRun { noAlias := true } seg87 (pcOf 87) 67
sym_block blk153 := symRun { noAlias := true } seg153 (pcOf 153) 9
sym_block blk161 := symRun { noAlias := true } seg161 (pcOf 161) 6
sym_block blk166 := symRun { noAlias := true } seg166 (pcOf 166) 4
sym_block blk169 := symRun { noAlias := true } seg169 (pcOf 169) 5
sym_block blk173 := symRun { noAlias := true } seg173 (pcOf 173) 6
sym_block blk178 := symRun { noAlias := true } seg178 (pcOf 178) 4
sym_block blk181 := symRun { noAlias := true } seg181 (pcOf 181) 3
sym_block blk183 := symRun { noAlias := true } seg183 (pcOf 183) 20
sym_block blk202 := symRun { noAlias := true } seg202 (pcOf 202) 17
sym_block blk218 := symRun { noAlias := true } seg218 (pcOf 218) 3
sym_block blk220 := symRun { noAlias := true } seg220 (pcOf 220) 4
sym_block blk223 := symRun { noAlias := true } seg223 (pcOf 223) 10
sym_block blk232 := symRun { noAlias := true } seg232 (pcOf 232) 12
sym_block blk243 := symRun { noAlias := true } seg243 (pcOf 243) 21
sym_block blk263 := symRun { noAlias := true } seg263 (pcOf 263) 3
sym_block blk265 := symRun { noAlias := true } seg265 (pcOf 265) 6
sym_block blk270 := symRun { noAlias := true } seg270 (pcOf 270) 2
sym_block blk271 := symRun { noAlias := true } seg271 (pcOf 271) 7
sym_block blk277 := symRun { noAlias := true } seg277 (pcOf 277) 3
sym_block blk279 := symRun { noAlias := true } seg279 (pcOf 279) 16
sym_block blk294 := symRun { noAlias := true } seg294 (pcOf 294) 6
sym_block blk299 := symRun { noAlias := true } seg299 (pcOf 299) 5
sym_block blk303 := symRun { noAlias := true } seg303 (pcOf 303) 22
sym_block blk324 := symRun { noAlias := true } seg324 (pcOf 324) 2
sym_block blk325 := symRun { noAlias := true } seg325 (pcOf 325) 3
sym_block blk327 := symRun { noAlias := true } seg327 (pcOf 327) 4
sym_block blk330 := symRun { noAlias := true } seg330 (pcOf 330) 128
sym_block blk457 := symRun { noAlias := true } seg457 (pcOf 457) 15
sym_block blk471 := symRun { noAlias := true } seg471 (pcOf 471) 8
sym_block blk478 := symRun { noAlias := true } seg478 (pcOf 478) 6
sym_block blk483 := symRun { noAlias := true } seg483 (pcOf 483) 5
sym_block blk487 := symRun { noAlias := true } seg487 (pcOf 487) 2
sym_block blk488 := symRun { noAlias := true } seg488 (pcOf 488) 7
sym_block blk494 := symRun { noAlias := true } seg494 (pcOf 494) 5
sym_block blk498 := symRun { noAlias := true } seg498 (pcOf 498) 3
sym_block blk500 := symRun { noAlias := true } seg500 (pcOf 500) 2
sym_block blk501 := symRun { noAlias := true } seg501 (pcOf 501) 7
sym_block blk507 := symRun { noAlias := true } seg507 (pcOf 507) 3
sym_block blk509 := symRun { noAlias := true } seg509 (pcOf 509) 10
sym_block blk518 := symRun { noAlias := true } seg518 (pcOf 518) 6
sym_block blk523 := symRun { noAlias := true } seg523 (pcOf 523) 3
sym_block blk525 := symRun { noAlias := true } seg525 (pcOf 525) 2
sym_block blk526 := symRun { noAlias := true } seg526 (pcOf 526) 20
sym_block blk545 := symRun { noAlias := true } seg545 (pcOf 545) 17
sym_block blk561 := symRun { noAlias := true } seg561 (pcOf 561) 3
sym_block blk563 := symRun { noAlias := true } seg563 (pcOf 563) 3
sym_block blk565 := symRun { noAlias := true } seg565 (pcOf 565) 8
sym_block blk572 := symRun { noAlias := true } seg572 (pcOf 572) 10
sym_block blk581 := symRun { noAlias := true } seg581 (pcOf 581) 6
sym_block blk586 := symRun { noAlias := true } seg586 (pcOf 586) 5
sym_block blk590 := symRun { noAlias := true } seg590 (pcOf 590) 2
sym_block blk591 := symRun { noAlias := true } seg591 (pcOf 591) 4
sym_block blk594 := symRun { noAlias := true } seg594 (pcOf 594) 4
sym_block blk597 := symRun { noAlias := true } seg597 (pcOf 597) 10
sym_block blk606 := symRun { noAlias := true } seg606 (pcOf 606) 5
sym_block blk610 := symRun { noAlias := true } seg610 (pcOf 610) 13
sym_block blk622 := symRun { noAlias := true } seg622 (pcOf 622) 18

end SigGolfCandidate.Sign
