-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackC0
import SigGolfCandidate.Sign.PackC1
import SigGolfCandidate.Sign.PackC2
import SigGolfCandidate.Sign.PackC3
import SigGolfCandidate.Sign.PackC4
import SigGolfCandidate.Sign.PackC5
import SigGolfCandidate.Sign.PackC6

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-- The whole pack (instructions 675 .. 2797). -/
theorem pack_run : PackStep 675 2798 0 491 2123 :=
  ((((((packStep_675.comp packStep_1114 (by norm_num)).comp packStep_1395 (by norm_num)).comp packStep_1706 (by norm_num)).comp packStep_2086 (by norm_num)).comp packStep_2298 (by norm_num)).comp packStep_2738 (by norm_num))

-- The final HALT.
sym_block blk2798 := symRun { noAlias := true } seg2798 (pcOf 2798) 4

end SigGolfCandidate.Sign
