-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC5

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 6: instructions 2781 .. 2840, signature dwords 480 .. 490. -/

set_option maxRecDepth 100000

sym_block blk2781 := symRun { noAlias := true } seg2781 (pcOf 2781) 61

kernel_theorem blk2781_pc : ∀ t : MachineState, (blk2781.res.toState t).pc = pcOf 2841
kernel_theorem blk2781_addrs : ∀ t : MachineState, blk2781.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 11).map (fun i => BitVec.ofNat 64 (packD + 8 * 480 + 8 * i))).reverse
kernel_theorem blk2781_words : ∀ t : MachineState,
    (blk2781.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 480)) 11 =
      ((packTab.drop 480).take 11).map (packDW t)

theorem packStep_2781 : PackStep 2781 2841 480 11 60 :=
  packStep_of blk2781 codeAt_2781 rfl blk2781_pc rfl rfl blk2781_words blk2781_addrs (by norm_num)

end SigGolfCandidate.Sign
