-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC3

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 4: instructions 2129 .. 2340, signature dwords 320 .. 399. -/

set_option maxRecDepth 100000

sym_block blk2129 := symRun { noAlias := true } seg2129 (pcOf 2129) 213

kernel_theorem blk2129_pc : ∀ t : MachineState, (blk2129.res.toState t).pc = pcOf 2341
kernel_theorem blk2129_addrs : ∀ t : MachineState, blk2129.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 320 + 8 * i))).reverse
kernel_theorem blk2129_words : ∀ t : MachineState,
    (blk2129.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 320)) 80 =
      ((packTab.drop 320).take 80).map (packDW t)

theorem packStep_2129 : PackStep 2129 2341 320 80 212 :=
  packStep_of blk2129 codeAt_2129 rfl blk2129_pc rfl rfl blk2129_words blk2129_addrs (by norm_num)

end SigGolfCandidate.Sign
