-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC5

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 6: instructions 2668 .. 2866, signature dwords 480 .. 559. -/

set_option maxRecDepth 100000

sym_block blk2668 := symRun { noAlias := true } seg2668 (pcOf 2668) 200

kernel_theorem blk2668_pc : ∀ t : MachineState, (blk2668.res.toState t).pc = pcOf 2867
kernel_theorem blk2668_addrs : ∀ t : MachineState, blk2668.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 480 + 8 * i))).reverse
kernel_theorem blk2668_words : ∀ t : MachineState,
    (blk2668.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 480)) 80 =
      ((packTab.drop 480).take 80).map (packDW t)

theorem packStep_2668 : PackStep 2668 2867 480 80 199 :=
  packStep_of blk2668 codeAt_2668 rfl blk2668_pc rfl rfl blk2668_words blk2668_addrs (by norm_num)

end SigGolfCandidate.Sign
