-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC3

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 4: instructions 1983 .. 2248, signature dwords 320 .. 399. -/

set_option maxRecDepth 100000

sym_block blk1983 := symRun { noAlias := true } seg1983 (pcOf 1983) 267

kernel_theorem blk1983_pc : ∀ t : MachineState, (blk1983.res.toState t).pc = pcOf 2249
kernel_theorem blk1983_addrs : ∀ t : MachineState, blk1983.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 320 + 8 * i))).reverse
kernel_theorem blk1983_words : ∀ t : MachineState,
    (blk1983.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 320)) 80 =
      ((packTab.drop 320).take 80).map (packDW t)

theorem packStep_1983 : PackStep 1983 2249 320 80 266 :=
  packStep_of blk1983 codeAt_1983 rfl blk1983_pc rfl rfl blk1983_words blk1983_addrs (by norm_num)

end SigGolfCandidate.Sign
