-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackC0
import SigGolfCandidate.Sign.PackC1
import SigGolfCandidate.Sign.PackC2
import SigGolfCandidate.Sign.PackC3
import SigGolfCandidate.Sign.PackC4
import SigGolfCandidate.Sign.PackC5
import SigGolfCandidate.Sign.PackC6
import SigGolfCandidate.Sign.PackC7
import SigGolfCandidate.Sign.PackC8

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-- The whole pack (instructions 611 .. 3391). -/
theorem pack_run : PackStep 611 3392 0 660 2781 :=
  ((((((((packStep_611.comp packStep_1050 (by norm_num)).comp packStep_1295 (by norm_num)).comp packStep_1648 (by norm_num)).comp packStep_1980 (by norm_num)).comp packStep_2246 (by norm_num)).comp packStep_2665 (by norm_num)).comp packStep_2864 (by norm_num)).comp packStep_3283 (by norm_num))

-- The final HALT.
sym_block blk3392 := symRun { noAlias := true } seg3392 (pcOf 3392) 4

end SigGolfCandidate.Sign
