-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC2

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 3: instructions 1749 .. 2128, signature dwords 240 .. 319. -/

set_option maxRecDepth 100000

sym_block blk1749 := symRun { noAlias := true } seg1749 (pcOf 1749) 381

kernel_theorem blk1749_pc : ∀ t : MachineState, (blk1749.res.toState t).pc = pcOf 2129
kernel_theorem blk1749_addrs : ∀ t : MachineState, blk1749.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 240 + 8 * i))).reverse
kernel_theorem blk1749_words : ∀ t : MachineState,
    (blk1749.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 240)) 80 =
      ((packTab.drop 240).take 80).map (packDW t)

theorem packStep_1749 : PackStep 1749 2129 240 80 380 :=
  packStep_of blk1749 codeAt_1749 rfl blk1749_pc rfl rfl blk1749_words blk1749_addrs (by norm_num)

end SigGolfCandidate.Sign
