-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackC0
import SigGolfCandidate.Sign.PackC1
import SigGolfCandidate.Sign.PackC2
import SigGolfCandidate.Sign.PackC3
import SigGolfCandidate.Sign.PackC4
import SigGolfCandidate.Sign.PackC5
import SigGolfCandidate.Sign.PackC6
import SigGolfCandidate.Sign.PackC7
import SigGolfCandidate.Sign.PackC8

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-- The whole pack (instructions 614 .. 3394). -/
theorem pack_run : PackStep 614 3395 0 660 2781 :=
  ((((((((packStep_614.comp packStep_1053 (by norm_num)).comp packStep_1298 (by norm_num)).comp packStep_1651 (by norm_num)).comp packStep_1983 (by norm_num)).comp packStep_2249 (by norm_num)).comp packStep_2668 (by norm_num)).comp packStep_2867 (by norm_num)).comp packStep_3286 (by norm_num))

-- The final HALT.
sym_block blk3395 := symRun { noAlias := true } seg3395 (pcOf 3395) 4

end SigGolfCandidate.Sign
