-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC7

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 8: instructions 3286 .. 3394, signature dwords 640 .. 659. -/

set_option maxRecDepth 100000

sym_block blk3286 := symRun { noAlias := true } seg3286 (pcOf 3286) 110

kernel_theorem blk3286_pc : ∀ t : MachineState, (blk3286.res.toState t).pc = pcOf 3395
kernel_theorem blk3286_addrs : ∀ t : MachineState, blk3286.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 20).map (fun i => BitVec.ofNat 64 (packD + 8 * 640 + 8 * i))).reverse
kernel_theorem blk3286_words : ∀ t : MachineState,
    (blk3286.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 640)) 20 =
      ((packTab.drop 640).take 20).map (packDW t)

theorem packStep_3286 : PackStep 3286 3395 640 20 109 :=
  packStep_of blk3286 codeAt_3286 rfl blk3286_pc rfl rfl blk3286_words blk3286_addrs (by norm_num)

end SigGolfCandidate.Sign
