-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC3

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 4: instructions 2077 .. 2288, signature dwords 320 .. 399. -/

set_option maxRecDepth 100000

sym_block blk2077 := symRun { noAlias := true } seg2077 (pcOf 2077) 213

kernel_theorem blk2077_pc : ∀ t : MachineState, (blk2077.res.toState t).pc = pcOf 2289
kernel_theorem blk2077_addrs : ∀ t : MachineState, blk2077.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 320 + 8 * i))).reverse
kernel_theorem blk2077_words : ∀ t : MachineState,
    (blk2077.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 320)) 80 =
      ((packTab.drop 320).take 80).map (packDW t)

theorem packStep_2077 : PackStep 2077 2289 320 80 212 :=
  packStep_of blk2077 codeAt_2077 rfl blk2077_pc rfl rfl blk2077_words blk2077_addrs (by norm_num)

end SigGolfCandidate.Sign
