-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC1

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 2: instructions 1386 .. 1696, signature dwords 160 .. 239. -/

set_option maxRecDepth 100000

sym_block blk1386 := symRun { noAlias := true } seg1386 (pcOf 1386) 312

kernel_theorem blk1386_pc : ∀ t : MachineState, (blk1386.res.toState t).pc = pcOf 1697
kernel_theorem blk1386_addrs : ∀ t : MachineState, blk1386.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 160 + 8 * i))).reverse
kernel_theorem blk1386_words : ∀ t : MachineState,
    (blk1386.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 160)) 80 =
      ((packTab.drop 160).take 80).map (packDW t)

theorem packStep_1386 : PackStep 1386 1697 160 80 311 :=
  packStep_of blk1386 codeAt_1386 rfl blk1386_pc rfl rfl blk1386_words blk1386_addrs (by norm_num)

end SigGolfCandidate.Sign
