-- Generated by SigGolfCandidate/Expand/gen_code.py from work/py-pors/out/expand.lst. Do not edit.
import SigGolfCandidate.Expand.Base
import SigGolfCandidate.Submission

namespace SigGolfCandidate.Expand
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

set_option maxRecDepth 16384

/-- instructions 0 .. 13 (start): lui gp, 0x1; addi gp, gp, -1023; sd gp, 32(x0); sd x0, 40(x0); lui s9, 0x3; addi s9, s9, 768 ... -/
def seg0 : List (BitVec 32) := [0x000011b7#32, 0xc0118193#32, 0x02303023#32, 0x02003423#32, 0x00003cb7#32, 0x300c8c93#32, 0x000cb083#32, 0x008cb103#32, 0x02103823#32, 0x02203c23#32, 0x02000513#32, 0x04000593#32, 0x16000613#32, 0x00000073#32]
/-- instructions 14 .. 17: lui tp, 0x400; sd tp, 1880(x0); addi s0, x0, 0; addi a6, x0, 34 -/
def seg14 : List (BitVec 32) := [0x00400237#32, 0x74403c23#32, 0x00000413#32, 0x02200813#32]
/-- instructions 18 .. 24 (da_ext): srli a3, a6, 6; slli a3, a3, 3; ld s1, 352(a3); srl s1, s1, a6; andi tp, a6, 63; addi a7, x0, 50 ... -/
def seg18 : List (BitVec 32) := [0x00685693#32, 0x00369693#32, 0x1606b483#32, 0x0104d4b3#32, 0x03f87213#32, 0x03200893#32, 0x0048dc63#32]
/-- instructions 25 .. 29: ld a4, 360(a3); addi a7, x0, 64; sub a7, a7, tp; sll a4, a4, a7; or s1, s1, a4 -/
def seg25 : List (BitVec 32) := [0x1686b703#32, 0x04000893#32, 0x404888b3#32, 0x01171733#32, 0x00e4e4b3#32]
/-- instructions 30 .. 39 (da_one): slli s1, s1, 50; srli s1, s1, 50; slli s1, s1, 8; slli gp, s0, 3; or s1, s1, gp; sd s1, 1760(gp) ... -/
def seg30 : List (BitVec 32) := [0x03249493#32, 0x0324d493#32, 0x00849493#32, 0x00341193#32, 0x0034e4b3#32, 0x6e91b023#32, 0x00e80813#32, 0x00140413#32, 0x00f00893#32, 0xfb1416e3#32]
/-- instructions 40 .. 40: addi s0, x0, 1 -/
def seg40 : List (BitVec 32) := [0x00100413#32]
/-- instructions 41 .. 43 (da_sort): slli a4, s0, 3; addi a4, a4, 1760; ld s1, 0(a4) -/
def seg41 : List (BitVec 32) := [0x00341713#32, 0x6e070713#32, 0x00073483#32]
/-- instructions 44 .. 45 (da_shift): addi a7, x0, 1760; beq a4, a7, +24 -/
def seg44 : List (BitVec 32) := [0x6e000893#32, 0x01170c63#32]
/-- instructions 46 .. 47: ld a3, -8(a4); bgeu s1, a3, +16 -/
def seg46 : List (BitVec 32) := [0xff873683#32, 0x00d4f863#32]
/-- instructions 48 .. 50: sd a3, 0(a4); addi a4, a4, -8; jal x0, -24 -/
def seg48 : List (BitVec 32) := [0x00d73023#32, 0xff870713#32, 0xfe9ff06f#32]
/-- instructions 51 .. 54 (da_place): sd s1, 0(a4); addi s0, s0, 1; addi a7, x0, 15; bne s0, a7, -52 -/
def seg51 : List (BitVec 32) := [0x00973023#32, 0x00140413#32, 0x00f00893#32, 0xfd1416e3#32]
/-- instructions 55 .. 56: addi s0, x0, 0; addi a5, x0, 0 -/
def seg55 : List (BitVec 32) := [0x00000413#32, 0x00000793#32]
/-- instructions 57 .. 63 (da_pass): slli gp, s0, 3; ld s1, 1760(gp); srli s1, s1, 8; ld a3, 1768(gp); srli a3, a3, 8; xor s1, s1, a3 ... -/
def seg57 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x00d4c4b3#32, 0x36048a63#32]
/-- instructions 64 .. 66 (bitlen_1): srli s1, s1, 1; addi a5, a5, 1; bne s1, x0, -8 -/
def seg64 : List (BitVec 32) := [0x0014d493#32, 0x00178793#32, 0xfe049ce3#32]
/-- instructions 67 .. 69: addi s0, s0, 1; addi a7, x0, 14; bne s0, a7, -48 -/
def seg67 : List (BitVec 32) := [0x00140413#32, 0x00e00893#32, 0xfd1418e3#32]
/-- instructions 70 .. 71: addi a7, x0, 134; blt a7, a5, +852 -/
def seg70 : List (BitVec 32) := [0x08600893#32, 0x34f8ca63#32]
/-- instructions 72 .. 80: lui t4, 0x3; addi t4, t4, 1024; lui t5, 0x1; addi t5, t5, -1776; addi t6, t5, 8; sd x0, 1888(x0) ... -/
def seg72 : List (BitVec 32) := [0x00003eb7#32, 0x400e8e93#32, 0x00001f37#32, 0x910f0f13#32, 0x008f0f93#32, 0x76003023#32, 0x76000b93#32, 0x00004c37#32, 0x00000413#32]
/-- instructions 81 .. 87 (sch_leaf): slli gp, s0, 3; ld s1, 1760(gp); srli s1, s1, 8; ld a3, 1768(gp); srli a3, a3, 8; xor a3, a3, s1 ... -/
def seg81 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x0096c6b3#32, 0xfff00a13#32]
/-- instructions 88 .. 90 (bitlen_2): srli a3, a3, 1; addi s4, s4, 1; bne a3, x0, -8 -/
def seg88 : List (BitVec 32) := [0x0016d693#32, 0x001a0a13#32, 0xfe069ce3#32]
/-- instructions 91 .. 94: or s2, s1, s8; andi a5, s2, 1; addi s3, x0, 0; addi s5, x0, 0 -/
def seg91 : List (BitVec 32) := [0x0184e933#32, 0x00197793#32, 0x00000993#32, 0x00000a93#32]
/-- instructions 95 .. 95 (sch_h): bge s3, s4, +96 -/
def seg95 : List (BitVec 32) := [0x0749d063#32]
/-- instructions 96 .. 97: ld gp, 0(s7); bne gp, s2, +48 -/
def seg96 : List (BitVec 32) := [0x000bb183#32, 0x03219863#32]
/-- instructions 98 .. 108: slli s9, a5, 5; or s9, s9, s5; ori s9, s9, 16; sb s9, 0(t5); addi t5, t6, 0; addi t6, t6, 8 ... -/
def seg98 : List (BitVec 32) := [0x00579c93#32, 0x015cecb3#32, 0x010cec93#32, 0x019f0023#32, 0x000f8f13#32, 0x008f8f93#32, 0x00000a93#32, 0xff8b8b93#32, 0x00195913#32, 0x00197793#32, 0x0240006f#32]
/-- instructions 109 .. 116 (sch_fold): ld ra, 0(t4); ld sp, 8(t4); sd ra, 0(t6); sd sp, 8(t6); addi t4, t4, 16; addi t6, t6, 16 ... -/
def seg109 : List (BitVec 32) := [0x000eb083#32, 0x008eb103#32, 0x001fb023#32, 0x002fb423#32, 0x010e8e93#32, 0x010f8f93#32, 0x001a8a93#32, 0x00195913#32]
/-- instructions 117 .. 118 (sch_next): addi s3, s3, 1; jal x0, -92 -/
def seg117 : List (BitVec 32) := [0x00198993#32, 0xfa5ff06f#32]
/-- instructions 119 .. 125 (sch_end): slli s9, a5, 5; or s9, s9, s5; sb s9, 0(t5); addi t5, t6, 0; addi t6, t6, 8; addi a7, x0, 14 ... -/
def seg119 : List (BitVec 32) := [0x00579c93#32, 0x015cecb3#32, 0x019f0023#32, 0x000f8f13#32, 0x008f8f93#32, 0x00e00893#32, 0x01140863#32]
/-- instructions 126 .. 128: xori gp, s2, 1; addi s7, s7, 8; sd gp, 0(s7) -/
def seg126 : List (BitVec 32) := [0x00194193#32, 0x008b8b93#32, 0x003bb023#32]
/-- instructions 129 .. 131 (sch_last): addi s0, s0, 1; addi a7, x0, 15; bne s0, a7, -200 -/
def seg129 : List (BitVec 32) := [0x00140413#32, 0x00f00893#32, 0xf3141ce3#32]
/-- instructions 132 .. 133: lui s9, 0x4; addi s9, s9, -1152 -/
def seg132 : List (BitVec 32) := [0x00004cb7#32, 0xb80c8c93#32]
/-- instructions 134 .. 134 (pad_loop): beq t4, s9, +20 -/
def seg134 : List (BitVec 32) := [0x019e8a63#32]
/-- instructions 135 .. 136: ld gp, 0(t4); bne gp, x0, +592 -/
def seg135 : List (BitVec 32) := [0x000eb183#32, 0x24019863#32]
/-- instructions 137 .. 138: addi t4, t4, 8; jal x0, -16 -/
def seg137 : List (BitVec 32) := [0x008e8e93#32, 0xff1ff06f#32]
/-- instructions 139 .. 143 (pad_ok): lui t1, 0x3; addi t1, t1, 768; lui t2, 0x1; addi t2, t2, -2048; addi s6, x0, 4 -/
def seg139 : List (BitVec 32) := [0x00003337#32, 0x30030313#32, 0x000013b7#32, 0x80038393#32, 0x00400b13#32]
/-- instructions 144 .. 149 (copy_rho_3): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg144 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 150 .. 152: lui s9, 0x1; addi s9, s9, -2032; addi s0, x0, 0 -/
def seg150 : List (BitVec 32) := [0x00001cb7#32, 0x810c8c93#32, 0x00000413#32]
/-- instructions 153 .. 159 (pi_loop): slli gp, s0, 3; ld s1, 1760(gp); add gp, s9, s0; sb s1, 0(gp); addi s0, s0, 1; addi a7, x0, 15 ... -/
def seg153 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x008c81b3#32, 0x00918023#32, 0x00140413#32, 0x00f00893#32, 0xff1414e3#32]
/-- instructions 160 .. 164: lui t1, 0x3; addi t1, t1, 784; lui t2, 0x1; addi t2, t2, -2016; addi s6, x0, 60 -/
def seg160 : List (BitVec 32) := [0x00003337#32, 0x31030313#32, 0x000013b7#32, 0x82038393#32, 0x03c00b13#32]
/-- instructions 165 .. 170 (copy_sec_4): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg165 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 171 .. 175: lui t1, 0x4; addi t1, t1, -1152; lui t2, 0x2; addi t2, t2, 184; addi s6, x0, 1 -/
def seg171 : List (BitVec 32) := [0x00004337#32, 0xb8030313#32, 0x000023b7#32, 0x0b838393#32, 0x00100b13#32]
/-- instructions 176 .. 181 (copy_ctr0_5): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg176 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 182 .. 186: lui t1, 0x4; addi t1, t1, -1148; lui t2, 0x1; addi t2, t2, 376; addi s6, x0, 212 -/
def seg182 : List (BitVec 32) := [0x00004337#32, 0xb8430313#32, 0x000013b7#32, 0x17838393#32, 0x0d400b13#32]
/-- instructions 187 .. 192 (copy_body0_6): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg187 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 193 .. 197: lui t1, 0x4; addi t1, t1, -300; lui t2, 0x2; addi t2, t2, 188; addi s6, x0, 1 -/
def seg193 : List (BitVec 32) := [0x00004337#32, 0xed430313#32, 0x000023b7#32, 0x0bc38393#32, 0x00100b13#32]
/-- instructions 198 .. 203 (copy_ctr1_7): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg198 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 204 .. 208: lui t1, 0x4; addi t1, t1, -296; lui t2, 0x1; addi t2, t2, 1224; addi s6, x0, 192 -/
def seg204 : List (BitVec 32) := [0x00004337#32, 0xed830313#32, 0x000013b7#32, 0x4c838393#32, 0x0c000b13#32]
/-- instructions 209 .. 214 (copy_body1_8): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg209 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 215 .. 219: lui t1, 0x4; addi t1, t1, 472; lui t2, 0x2; addi t2, t2, 192; addi s6, x0, 1 -/
def seg215 : List (BitVec 32) := [0x00004337#32, 0x1d830313#32, 0x000023b7#32, 0x0c038393#32, 0x00100b13#32]
/-- instructions 220 .. 225 (copy_ctr2_9): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg220 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 226 .. 230: lui t1, 0x4; addi t1, t1, 476; lui t2, 0x1; addi t2, t2, 1992; addi s6, x0, 192 -/
def seg226 : List (BitVec 32) := [0x00004337#32, 0x1dc30313#32, 0x000013b7#32, 0x7c838393#32, 0x0c000b13#32]
/-- instructions 231 .. 236 (copy_body2_10): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg231 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 237 .. 241: lui t1, 0x4; addi t1, t1, 1244; lui t2, 0x2; addi t2, t2, 196; addi s6, x0, 1 -/
def seg237 : List (BitVec 32) := [0x00004337#32, 0x4dc30313#32, 0x000023b7#32, 0x0c438393#32, 0x00100b13#32]
/-- instructions 242 .. 247 (copy_ctr3_11): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg242 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 248 .. 252: lui t1, 0x4; addi t1, t1, 1248; lui t2, 0x2; addi t2, t2, -1336; addi s6, x0, 192 -/
def seg248 : List (BitVec 32) := [0x00004337#32, 0x4e030313#32, 0x000023b7#32, 0xac838393#32, 0x0c000b13#32]
/-- instructions 253 .. 258 (copy_body3_12): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg253 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 259 .. 263: lui t1, 0x4; addi t1, t1, 2016; lui t2, 0x2; addi t2, t2, 200; addi s6, x0, 1 -/
def seg259 : List (BitVec 32) := [0x00004337#32, 0x7e030313#32, 0x000023b7#32, 0x0c838393#32, 0x00100b13#32]
/-- instructions 264 .. 269 (copy_ctr4_13): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg264 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 270 .. 274: lui t1, 0x4; addi t1, t1, 2020; lui t2, 0x2; addi t2, t2, -568; addi s6, x0, 188 -/
def seg270 : List (BitVec 32) := [0x00004337#32, 0x7e430313#32, 0x000023b7#32, 0xdc838393#32, 0x0bc00b13#32]
/-- instructions 275 .. 280 (copy_body4_14): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg275 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 281 .. 283: addi t0, x0, 1; addi a0, x0, 0; ecall  -/
def seg281 : List (BitVec 32) := [0x00100293#32, 0x00000513#32, 0x00000073#32]
/-- instructions 284 .. 286 (fail): addi t0, x0, 1; addi a0, x0, 1; ecall  -/
def seg284 : List (BitVec 32) := [0x00100293#32, 0x00100513#32, 0x00000073#32]

/-- Segment table of the expand image. -/
def L : Rv.Layout := [(0, seg0), (14, seg14), (18, seg18), (25, seg25), (30, seg30), (40, seg40), (41, seg41), (44, seg44), (46, seg46), (48, seg48), (51, seg51), (55, seg55), (57, seg57), (64, seg64), (67, seg67), (70, seg70), (72, seg72), (81, seg81), (88, seg88), (91, seg91), (95, seg95), (96, seg96), (98, seg98), (109, seg109), (117, seg117), (119, seg119), (126, seg126), (129, seg129), (132, seg132), (134, seg134), (135, seg135), (137, seg137), (139, seg139), (144, seg144), (150, seg150), (153, seg153), (160, seg160), (165, seg165), (171, seg171), (176, seg176), (182, seg182), (187, seg187), (193, seg193), (198, seg198), (204, seg204), (209, seg209), (215, seg215), (220, seg220), (226, seg226), (231, seg231), (237, seg237), (242, seg242), (248, seg248), (253, seg253), (259, seg259), (264, seg264), (270, seg270), (275, seg275), (281, seg281), (284, seg284)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The expand image. -/
abbrev image : Image := Images.expandImage

theorem image_eq : submission.image .expand = image := rfl

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (pcOf 0) seg0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_14 : CodeAt image (pcOf 14) seg14 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_18 : CodeAt image (pcOf 18) seg18 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (pcOf 25) seg25 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_30 : CodeAt image (pcOf 30) seg30 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_40 : CodeAt image (pcOf 40) seg40 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_41 : CodeAt image (pcOf 41) seg41 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_44 : CodeAt image (pcOf 44) seg44 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_46 : CodeAt image (pcOf 46) seg46 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_48 : CodeAt image (pcOf 48) seg48 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_51 : CodeAt image (pcOf 51) seg51 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_55 : CodeAt image (pcOf 55) seg55 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (pcOf 57) seg57 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_64 : CodeAt image (pcOf 64) seg64 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_67 : CodeAt image (pcOf 67) seg67 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (pcOf 70) seg70 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_72 : CodeAt image (pcOf 72) seg72 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_81 : CodeAt image (pcOf 81) seg81 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_88 : CodeAt image (pcOf 88) seg88 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_91 : CodeAt image (pcOf 91) seg91 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_95 : CodeAt image (pcOf 95) seg95 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_96 : CodeAt image (pcOf 96) seg96 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_98 : CodeAt image (pcOf 98) seg98 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_109 : CodeAt image (pcOf 109) seg109 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_117 : CodeAt image (pcOf 117) seg117 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_119 : CodeAt image (pcOf 119) seg119 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_126 : CodeAt image (pcOf 126) seg126 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_129 : CodeAt image (pcOf 129) seg129 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_132 : CodeAt image (pcOf 132) seg132 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_134 : CodeAt image (pcOf 134) seg134 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_135 : CodeAt image (pcOf 135) seg135 :=
  codeAt_layout code_eq layout_ok (i := 30) (by kernel_rfl) (by decide)
theorem codeAt_137 : CodeAt image (pcOf 137) seg137 :=
  codeAt_layout code_eq layout_ok (i := 31) (by kernel_rfl) (by decide)
theorem codeAt_139 : CodeAt image (pcOf 139) seg139 :=
  codeAt_layout code_eq layout_ok (i := 32) (by kernel_rfl) (by decide)
theorem codeAt_144 : CodeAt image (pcOf 144) seg144 :=
  codeAt_layout code_eq layout_ok (i := 33) (by kernel_rfl) (by decide)
theorem codeAt_150 : CodeAt image (pcOf 150) seg150 :=
  codeAt_layout code_eq layout_ok (i := 34) (by kernel_rfl) (by decide)
theorem codeAt_153 : CodeAt image (pcOf 153) seg153 :=
  codeAt_layout code_eq layout_ok (i := 35) (by kernel_rfl) (by decide)
theorem codeAt_160 : CodeAt image (pcOf 160) seg160 :=
  codeAt_layout code_eq layout_ok (i := 36) (by kernel_rfl) (by decide)
theorem codeAt_165 : CodeAt image (pcOf 165) seg165 :=
  codeAt_layout code_eq layout_ok (i := 37) (by kernel_rfl) (by decide)
theorem codeAt_171 : CodeAt image (pcOf 171) seg171 :=
  codeAt_layout code_eq layout_ok (i := 38) (by kernel_rfl) (by decide)
theorem codeAt_176 : CodeAt image (pcOf 176) seg176 :=
  codeAt_layout code_eq layout_ok (i := 39) (by kernel_rfl) (by decide)
theorem codeAt_182 : CodeAt image (pcOf 182) seg182 :=
  codeAt_layout code_eq layout_ok (i := 40) (by kernel_rfl) (by decide)
theorem codeAt_187 : CodeAt image (pcOf 187) seg187 :=
  codeAt_layout code_eq layout_ok (i := 41) (by kernel_rfl) (by decide)
theorem codeAt_193 : CodeAt image (pcOf 193) seg193 :=
  codeAt_layout code_eq layout_ok (i := 42) (by kernel_rfl) (by decide)
theorem codeAt_198 : CodeAt image (pcOf 198) seg198 :=
  codeAt_layout code_eq layout_ok (i := 43) (by kernel_rfl) (by decide)
theorem codeAt_204 : CodeAt image (pcOf 204) seg204 :=
  codeAt_layout code_eq layout_ok (i := 44) (by kernel_rfl) (by decide)
theorem codeAt_209 : CodeAt image (pcOf 209) seg209 :=
  codeAt_layout code_eq layout_ok (i := 45) (by kernel_rfl) (by decide)
theorem codeAt_215 : CodeAt image (pcOf 215) seg215 :=
  codeAt_layout code_eq layout_ok (i := 46) (by kernel_rfl) (by decide)
theorem codeAt_220 : CodeAt image (pcOf 220) seg220 :=
  codeAt_layout code_eq layout_ok (i := 47) (by kernel_rfl) (by decide)
theorem codeAt_226 : CodeAt image (pcOf 226) seg226 :=
  codeAt_layout code_eq layout_ok (i := 48) (by kernel_rfl) (by decide)
theorem codeAt_231 : CodeAt image (pcOf 231) seg231 :=
  codeAt_layout code_eq layout_ok (i := 49) (by kernel_rfl) (by decide)
theorem codeAt_237 : CodeAt image (pcOf 237) seg237 :=
  codeAt_layout code_eq layout_ok (i := 50) (by kernel_rfl) (by decide)
theorem codeAt_242 : CodeAt image (pcOf 242) seg242 :=
  codeAt_layout code_eq layout_ok (i := 51) (by kernel_rfl) (by decide)
theorem codeAt_248 : CodeAt image (pcOf 248) seg248 :=
  codeAt_layout code_eq layout_ok (i := 52) (by kernel_rfl) (by decide)
theorem codeAt_253 : CodeAt image (pcOf 253) seg253 :=
  codeAt_layout code_eq layout_ok (i := 53) (by kernel_rfl) (by decide)
theorem codeAt_259 : CodeAt image (pcOf 259) seg259 :=
  codeAt_layout code_eq layout_ok (i := 54) (by kernel_rfl) (by decide)
theorem codeAt_264 : CodeAt image (pcOf 264) seg264 :=
  codeAt_layout code_eq layout_ok (i := 55) (by kernel_rfl) (by decide)
theorem codeAt_270 : CodeAt image (pcOf 270) seg270 :=
  codeAt_layout code_eq layout_ok (i := 56) (by kernel_rfl) (by decide)
theorem codeAt_275 : CodeAt image (pcOf 275) seg275 :=
  codeAt_layout code_eq layout_ok (i := 57) (by kernel_rfl) (by decide)
theorem codeAt_281 : CodeAt image (pcOf 281) seg281 :=
  codeAt_layout code_eq layout_ok (i := 58) (by kernel_rfl) (by decide)
theorem codeAt_284 : CodeAt image (pcOf 284) seg284 :=
  codeAt_layout code_eq layout_ok (i := 59) (by kernel_rfl) (by decide)

end SigGolfCandidate.Expand
