-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC3

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 4: instructions 2086 .. 2297, signature dwords 320 .. 399. -/

set_option maxRecDepth 100000

sym_block blk2086 := symRun { noAlias := true } seg2086 (pcOf 2086) 213

kernel_theorem blk2086_pc : ∀ t : MachineState, (blk2086.res.toState t).pc = pcOf 2298
kernel_theorem blk2086_addrs : ∀ t : MachineState, blk2086.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 320 + 8 * i))).reverse
kernel_theorem blk2086_words : ∀ t : MachineState,
    (blk2086.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 320)) 80 =
      ((packTab.drop 320).take 80).map (packDW t)

theorem packStep_2086 : PackStep 2086 2298 320 80 212 :=
  packStep_of blk2086 codeAt_2086 rfl blk2086_pc rfl rfl blk2086_words blk2086_addrs (by norm_num)

end SigGolfCandidate.Sign
