import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (36, 41, 58, 87, 118, 157, 160) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00b00493, 0x000049b7, 0x4c098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x2011ee93, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13, 0x0e003023, 0x0e003423]
def seg_25 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_32 : List (BitVec 32) := [0x6b502223, 0x6a000513, 0x04000593, 0x0f000613]
def seg_36 : List (BitVec 32) := [0x00000073]
def seg_37 : List (BitVec 32) := [0x00000b93]
def seg_38 : List (BitVec 32) := [0x001b8b93, 0x0d802223, 0x0c000513]
def seg_41 : List (BitVec 32) := [0x00000073]
def seg_42 : List (BitVec 32) := [0x001c0c13, 0x00700193, 0xfe3b94e3]
def seg_45 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0f003083, 0x0f803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xfa3a96e3]
def seg_54 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_58 : List (BitVec 32) := [0x00000073]
def seg_59 : List (BitVec 32) := [0x001a0a13, 0xf71a1ae3]
def seg_61 : List (BitVec 32) := [0x00100793]
def seg_62 : List (BitVec 32) := [0x02079193, 0x01041e93, 0x01d1e1b3, 0x3011e193, 0x1c303023, 0x1de02423, 0x00489193, 0x00398cb3, 0x0018d893, 0x00000813]
def seg_72 : List (BitVec 32) := [0x1d002623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x003c8633]
def seg_87 : List (BitVec 32) := [0x00000073]
def seg_88 : List (BitVec 32) := [0x00180813, 0xfb181ee3]
def seg_90 : List (BitVec 32) := [0x000c8993, 0x00178793, 0xf8f4d4e3]
def seg_93 : List (BitVec 32) := [0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x0009b023, 0x0009b423, 0x0009b823, 0x0009bc23]
def seg_101 : List (BitVec 32) := [0x00004a37, 0x4c0a0a13, 0x00000793]
def seg_104 : List (BitVec 32) := [0x00100193, 0x00b00e93, 0x40fe8eb3, 0x01d198b3, 0x00000813]
def seg_109 : List (BitVec 32) := [0x02079193, 0x68118193, 0x68018193, 0x6a303023, 0x02081193, 0x6a303423, 0x6a000513, 0x04000593, 0x14000613]
def seg_118 : List (BitVec 32) := [0x00000073]
def seg_119 : List (BitVec 32) := [0x000a3083, 0x14003103, 0x0020c0b3, 0x001a3023, 0x008a3083, 0x14803103, 0x0020c0b3, 0x001a3423, 0x010a0a13, 0x00180813, 0xfb1818e3]
def seg_130 : List (BitVec 32) := [0x00178793, 0x00b00193, 0xf83798e3]
def seg_133 : List (BitVec 32) := [0x00004eb7, 0x4a0e8e93, 0x000011b7, 0xe0118193, 0xfe3eb023, 0x08003083, 0x001eb023, 0x08803083, 0x001eb423, 0x09003083, 0x001eb823, 0x09803083, 0x001ebc23, 0x000141b7, 0x4a018193, 0x0001b023, 0x0001b423, 0x0001b823, 0x0001bc23, 0xfe0e8513, 0x000105b7, 0x04058593, 0x00004637, 0x4a060613]
def seg_157 : List (BitVec 32) := [0x00000073]
def seg_158 : List (BitVec 32) := [0x00100293, 0x00000513]
def seg_160 : List (BitVec 32) := [0x00000073]

def L : Rv.Layout := [(0, seg_0), (25, seg_25), (32, seg_32), (36, seg_36), (37, seg_37), (38, seg_38), (41, seg_41), (42, seg_42), (45, seg_45), (54, seg_54), (58, seg_58), (59, seg_59), (61, seg_61), (62, seg_62), (72, seg_72), (87, seg_87), (88, seg_88), (90, seg_90), (93, seg_93), (101, seg_101), (104, seg_104), (109, seg_109), (118, seg_118), (119, seg_119), (130, seg_130), (133, seg_133), (157, seg_157), (158, seg_158), (160, seg_160)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 25)) seg_25 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_32 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) seg_32 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_36 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 36)) seg_36 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_37 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 37)) seg_37 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_38 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 38)) seg_38 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_41 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 41)) seg_41 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_42 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 42)) seg_42 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_45 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 45)) seg_45 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_54 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 54)) seg_54 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_58 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 58)) seg_58 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_59 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 59)) seg_59 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_61 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 61)) seg_61 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_62 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 62)) seg_62 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_72 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 72)) seg_72 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_87 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 87)) seg_87 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_88 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 88)) seg_88 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_90 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 90)) seg_90 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_93 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 93)) seg_93 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_101 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 101)) seg_101 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 104)) seg_104 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_109 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 109)) seg_109 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_118 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 118)) seg_118 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_119 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 119)) seg_119 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_130 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 130)) seg_130 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_133 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 133)) seg_133 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_157 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 157)) seg_157 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_158 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 158)) seg_158 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_160 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 160)) seg_160 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)

sym_block blk_0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 100
sym_block blk_25 := symRun { noAlias := true } seg_25 (BitVec.ofNat 64 (0x1000 + 4 * 25)) 100
sym_block blk_32 := symRun { noAlias := true } seg_32 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 100
sym_block blk_37 := symRun { noAlias := true } seg_37 (BitVec.ofNat 64 (0x1000 + 4 * 37)) 100
sym_block blk_38 := symRun { noAlias := true } seg_38 (BitVec.ofNat 64 (0x1000 + 4 * 38)) 100
sym_block blk_42 := symRun { noAlias := true } seg_42 (BitVec.ofNat 64 (0x1000 + 4 * 42)) 100
sym_block blk_45 := symRun { noAlias := true } seg_45 (BitVec.ofNat 64 (0x1000 + 4 * 45)) 100
sym_block blk_54 := symRun { noAlias := true } seg_54 (BitVec.ofNat 64 (0x1000 + 4 * 54)) 100
sym_block blk_59 := symRun { noAlias := true } seg_59 (BitVec.ofNat 64 (0x1000 + 4 * 59)) 100
sym_block blk_61 := symRun { noAlias := true } seg_61 (BitVec.ofNat 64 (0x1000 + 4 * 61)) 100
sym_block blk_62 := symRun { noAlias := true } seg_62 (BitVec.ofNat 64 (0x1000 + 4 * 62)) 100
sym_block blk_72 := symRun { noAlias := true } seg_72 (BitVec.ofNat 64 (0x1000 + 4 * 72)) 100
sym_block blk_88 := symRun { noAlias := true } seg_88 (BitVec.ofNat 64 (0x1000 + 4 * 88)) 100
sym_block blk_90 := symRun { noAlias := true } seg_90 (BitVec.ofNat 64 (0x1000 + 4 * 90)) 100
sym_block blk_93 := symRun { noAlias := true } seg_93 (BitVec.ofNat 64 (0x1000 + 4 * 93)) 100
sym_block blk_101 := symRun { noAlias := true } seg_101 (BitVec.ofNat 64 (0x1000 + 4 * 101)) 100
sym_block blk_104 := symRun { noAlias := true } seg_104 (BitVec.ofNat 64 (0x1000 + 4 * 104)) 100
sym_block blk_109 := symRun { noAlias := true } seg_109 (BitVec.ofNat 64 (0x1000 + 4 * 109)) 100
sym_block blk_119 := symRun { noAlias := true } seg_119 (BitVec.ofNat 64 (0x1000 + 4 * 119)) 100
sym_block blk_130 := symRun { noAlias := true } seg_130 (BitVec.ofNat 64 (0x1000 + 4 * 130)) 100
sym_block blk_133 := symRun { noAlias := true } seg_133 (BitVec.ofNat 64 (0x1000 + 4 * 133)) 100
sym_block blk_158 := symRun { noAlias := true } seg_158 (BitVec.ofNat 64 (0x1000 + 4 * 158)) 100

end SigGolfCandidate.Keygen
