-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC4

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 5: instructions 2249 .. 2667, signature dwords 400 .. 479. -/

set_option maxRecDepth 100000

sym_block blk2249 := symRun { noAlias := true } seg2249 (pcOf 2249) 420

kernel_theorem blk2249_pc : ∀ t : MachineState, (blk2249.res.toState t).pc = pcOf 2668
kernel_theorem blk2249_addrs : ∀ t : MachineState, blk2249.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 400 + 8 * i))).reverse
kernel_theorem blk2249_words : ∀ t : MachineState,
    (blk2249.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 400)) 80 =
      ((packTab.drop 400).take 80).map (packDW t)

theorem packStep_2249 : PackStep 2249 2668 400 80 419 :=
  packStep_of blk2249 codeAt_2249 rfl blk2249_pc rfl rfl blk2249_words blk2249_addrs (by norm_num)

end SigGolfCandidate.Sign
