-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep
import SigGolfCandidate.Sign.PackC1

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 2: instructions 1298 .. 1650, signature dwords 160 .. 239. -/

set_option maxRecDepth 100000

sym_block blk1298 := symRun { noAlias := true } seg1298 (pcOf 1298) 354

kernel_theorem blk1298_pc : ∀ t : MachineState, (blk1298.res.toState t).pc = pcOf 1651
kernel_theorem blk1298_addrs : ∀ t : MachineState, blk1298.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 160 + 8 * i))).reverse
kernel_theorem blk1298_words : ∀ t : MachineState,
    (blk1298.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 160)) 80 =
      ((packTab.drop 160).take 80).map (packDW t)

theorem packStep_1298 : PackStep 1298 1651 160 80 353 :=
  packStep_of blk1298 codeAt_1298 rfl blk1298_pc rfl rfl blk1298_words blk1298_addrs (by norm_num)

end SigGolfCandidate.Sign
