import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (39, 56, 73, 101, 132, 171, 174) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00b00493, 0x000059b7, 0xb2098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x2011ee93, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13, 0x0e003023, 0x0e003423]
def seg_25 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_32 : List (BitVec 32) := [0x001af193, 0x00019e63]
def seg_34 : List (BitVec 32) := [0x001ad193, 0x6a302223, 0x6a000513, 0x04000593, 0x14000613]
def seg_39 : List (BitVec 32) := [0x00000073]
def seg_40 : List (BitVec 32) := [0x001af193, 0x00419193, 0x1401b083, 0x1481b103, 0x0e103823, 0x0e203c23, 0x0c000513, 0x0f000613, 0x00000b93]
def seg_49 : List (BitVec 32) := [0x001b8b93, 0x003c5193, 0x00819193, 0x007c7e93, 0x01d1e1b3, 0x0c302223, 0x0c000513]
def seg_56 : List (BitVec 32) := [0x00000073]
def seg_57 : List (BitVec 32) := [0x001c0c13, 0x00700193, 0xfc3b9ce3]
def seg_60 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0f003083, 0x0f803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xf63a98e3]
def seg_69 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_73 : List (BitVec 32) := [0x00000073]
def seg_74 : List (BitVec 32) := [0x001a0a13, 0xf31a1ce3]
def seg_76 : List (BitVec 32) := [0x00100793]
def seg_77 : List (BitVec 32) := [0x01041193, 0x3011e193, 0x1c303023, 0x1de02423, 0x00489193, 0x00398cb3, 0x0018d893, 0x00000813]
def seg_85 : List (BitVec 32) := [0x01180133, 0x1c202623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x003c8633]
def seg_101 : List (BitVec 32) := [0x00000073]
def seg_102 : List (BitVec 32) := [0x00180813, 0xfb181ce3]
def seg_104 : List (BitVec 32) := [0x000c8993, 0x00178793, 0xf8f4d6e3]
def seg_107 : List (BitVec 32) := [0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x0009b023, 0x0009b423, 0x0009b823, 0x0009bc23]
def seg_115 : List (BitVec 32) := [0x00005a37, 0xb20a0a13, 0x00000793]
def seg_118 : List (BitVec 32) := [0x00100193, 0x00b00e93, 0x40fe8eb3, 0x01d198b3, 0x00000813]
def seg_123 : List (BitVec 32) := [0x02079193, 0x68118193, 0x68018193, 0x6a303023, 0x02081193, 0x6a303423, 0x6a000513, 0x04000593, 0x14000613]
def seg_132 : List (BitVec 32) := [0x00000073]
def seg_133 : List (BitVec 32) := [0x000a3083, 0x14003103, 0x0020c0b3, 0x001a3023, 0x008a3083, 0x14803103, 0x0020c0b3, 0x001a3423, 0x010a0a13, 0x00180813, 0xfb1818e3]
def seg_144 : List (BitVec 32) := [0x00178793, 0x00b00193, 0xf83798e3]
def seg_147 : List (BitVec 32) := [0x00005eb7, 0xb00e8e93, 0x000011b7, 0xe0118193, 0xfe3eb023, 0x08003083, 0x001eb023, 0x08803083, 0x001eb423, 0x09003083, 0x001eb823, 0x09803083, 0x001ebc23, 0x000151b7, 0xb0018193, 0x0001b023, 0x0001b423, 0x0001b823, 0x0001bc23, 0xfe0e8513, 0x000105b7, 0x04058593, 0x00005637, 0xb0060613]
def seg_171 : List (BitVec 32) := [0x00000073]
def seg_172 : List (BitVec 32) := [0x00100293, 0x00000513]
def seg_174 : List (BitVec 32) := [0x00000073]

def L : Rv.Layout := [(0, seg_0), (25, seg_25), (32, seg_32), (34, seg_34), (39, seg_39), (40, seg_40), (49, seg_49), (56, seg_56), (57, seg_57), (60, seg_60), (69, seg_69), (73, seg_73), (74, seg_74), (76, seg_76), (77, seg_77), (85, seg_85), (101, seg_101), (102, seg_102), (104, seg_104), (107, seg_107), (115, seg_115), (118, seg_118), (123, seg_123), (132, seg_132), (133, seg_133), (144, seg_144), (147, seg_147), (171, seg_171), (172, seg_172), (174, seg_174)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 25)) seg_25 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_32 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) seg_32 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_34 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 34)) seg_34 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_39 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 39)) seg_39 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_40 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 40)) seg_40 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_49 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 49)) seg_49 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_56 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 56)) seg_56 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 57)) seg_57 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_60 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 60)) seg_60 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_69 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 69)) seg_69 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_73 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 73)) seg_73 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_74 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 74)) seg_74 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_76 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 76)) seg_76 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_77 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 77)) seg_77 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_85 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 85)) seg_85 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_101 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 101)) seg_101 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_102 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 102)) seg_102 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 104)) seg_104 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_107 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 107)) seg_107 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_115 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 115)) seg_115 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_118 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 118)) seg_118 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_123 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 123)) seg_123 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_132 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 132)) seg_132 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_133 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 133)) seg_133 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_144 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 144)) seg_144 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_147 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 147)) seg_147 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_171 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 171)) seg_171 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_172 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 172)) seg_172 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_174 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 174)) seg_174 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)

sym_block blk_0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 100
sym_block blk_25 := symRun { noAlias := true } seg_25 (BitVec.ofNat 64 (0x1000 + 4 * 25)) 100
sym_block blk_32 := symRun { noAlias := true } seg_32 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 100
sym_block blk_34 := symRun { noAlias := true } seg_34 (BitVec.ofNat 64 (0x1000 + 4 * 34)) 100
sym_block blk_40 := symRun { noAlias := true } seg_40 (BitVec.ofNat 64 (0x1000 + 4 * 40)) 100
sym_block blk_49 := symRun { noAlias := true } seg_49 (BitVec.ofNat 64 (0x1000 + 4 * 49)) 100
sym_block blk_57 := symRun { noAlias := true } seg_57 (BitVec.ofNat 64 (0x1000 + 4 * 57)) 100
sym_block blk_60 := symRun { noAlias := true } seg_60 (BitVec.ofNat 64 (0x1000 + 4 * 60)) 100
sym_block blk_69 := symRun { noAlias := true } seg_69 (BitVec.ofNat 64 (0x1000 + 4 * 69)) 100
sym_block blk_74 := symRun { noAlias := true } seg_74 (BitVec.ofNat 64 (0x1000 + 4 * 74)) 100
sym_block blk_76 := symRun { noAlias := true } seg_76 (BitVec.ofNat 64 (0x1000 + 4 * 76)) 100
sym_block blk_77 := symRun { noAlias := true } seg_77 (BitVec.ofNat 64 (0x1000 + 4 * 77)) 100
sym_block blk_85 := symRun { noAlias := true } seg_85 (BitVec.ofNat 64 (0x1000 + 4 * 85)) 100
sym_block blk_102 := symRun { noAlias := true } seg_102 (BitVec.ofNat 64 (0x1000 + 4 * 102)) 100
sym_block blk_104 := symRun { noAlias := true } seg_104 (BitVec.ofNat 64 (0x1000 + 4 * 104)) 100
sym_block blk_107 := symRun { noAlias := true } seg_107 (BitVec.ofNat 64 (0x1000 + 4 * 107)) 100
sym_block blk_115 := symRun { noAlias := true } seg_115 (BitVec.ofNat 64 (0x1000 + 4 * 115)) 100
sym_block blk_118 := symRun { noAlias := true } seg_118 (BitVec.ofNat 64 (0x1000 + 4 * 118)) 100
sym_block blk_123 := symRun { noAlias := true } seg_123 (BitVec.ofNat 64 (0x1000 + 4 * 123)) 100
sym_block blk_133 := symRun { noAlias := true } seg_133 (BitVec.ofNat 64 (0x1000 + 4 * 133)) 100
sym_block blk_144 := symRun { noAlias := true } seg_144 (BitVec.ofNat 64 (0x1000 + 4 * 144)) 100
sym_block blk_147 := symRun { noAlias := true } seg_147 (BitVec.ofNat 64 (0x1000 + 4 * 147)) 100
sym_block blk_172 := symRun { noAlias := true } seg_172 (BitVec.ofNat 64 (0x1000 + 4 * 172)) 100

end SigGolfCandidate.Keygen
