-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.Code

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Symbolic blocks of the sign program (before the pack). -/

sym_block blk0 := symRun { noAlias := true } seg0 (pcOf 0) 28
sym_block blk27 := symRun { noAlias := true } seg27 (pcOf 27) 6
sym_block blk32 := symRun { noAlias := true } seg32 (pcOf 32) 6
sym_block blk37 := symRun { noAlias := true } seg37 (pcOf 37) 5
sym_block blk41 := symRun { noAlias := true } seg41 (pcOf 41) 3
sym_block blk43 := symRun { noAlias := true } seg43 (pcOf 43) 4
sym_block blk46 := symRun { noAlias := true } seg46 (pcOf 46) 67
sym_block blk112 := symRun { noAlias := true } seg112 (pcOf 112) 9
sym_block blk120 := symRun { noAlias := true } seg120 (pcOf 120) 6
sym_block blk125 := symRun { noAlias := true } seg125 (pcOf 125) 4
sym_block blk128 := symRun { noAlias := true } seg128 (pcOf 128) 5
sym_block blk132 := symRun { noAlias := true } seg132 (pcOf 132) 6
sym_block blk137 := symRun { noAlias := true } seg137 (pcOf 137) 4
sym_block blk140 := symRun { noAlias := true } seg140 (pcOf 140) 3
sym_block blk142 := symRun { noAlias := true } seg142 (pcOf 142) 20
sym_block blk161 := symRun { noAlias := true } seg161 (pcOf 161) 17
sym_block blk177 := symRun { noAlias := true } seg177 (pcOf 177) 3
sym_block blk179 := symRun { noAlias := true } seg179 (pcOf 179) 4
sym_block blk182 := symRun { noAlias := true } seg182 (pcOf 182) 10
sym_block blk191 := symRun { noAlias := true } seg191 (pcOf 191) 12
sym_block blk202 := symRun { noAlias := true } seg202 (pcOf 202) 4
sym_block blk205 := symRun { noAlias := true } seg205 (pcOf 205) 3
sym_block blk207 := symRun { noAlias := true } seg207 (pcOf 207) 4
sym_block blk210 := symRun { noAlias := true } seg210 (pcOf 210) 6
sym_block blk215 := symRun { noAlias := true } seg215 (pcOf 215) 16
sym_block blk230 := symRun { noAlias := true } seg230 (pcOf 230) 6
sym_block blk235 := symRun { noAlias := true } seg235 (pcOf 235) 4
sym_block blk238 := symRun { noAlias := true } seg238 (pcOf 238) 2
sym_block blk239 := symRun { noAlias := true } seg239 (pcOf 239) 126
sym_block blk364 := symRun { noAlias := true } seg364 (pcOf 364) 2
sym_block blk365 := symRun { noAlias := true } seg365 (pcOf 365) 3
sym_block blk367 := symRun { noAlias := true } seg367 (pcOf 367) 4
sym_block blk370 := symRun { noAlias := true } seg370 (pcOf 370) 139
sym_block blk508 := symRun { noAlias := true } seg508 (pcOf 508) 8
sym_block blk515 := symRun { noAlias := true } seg515 (pcOf 515) 6
sym_block blk520 := symRun { noAlias := true } seg520 (pcOf 520) 7
sym_block blk526 := symRun { noAlias := true } seg526 (pcOf 526) 2
sym_block blk527 := symRun { noAlias := true } seg527 (pcOf 527) 7
sym_block blk533 := symRun { noAlias := true } seg533 (pcOf 533) 6
sym_block blk538 := symRun { noAlias := true } seg538 (pcOf 538) 5
sym_block blk542 := symRun { noAlias := true } seg542 (pcOf 542) 2
sym_block blk543 := symRun { noAlias := true } seg543 (pcOf 543) 7
sym_block blk549 := symRun { noAlias := true } seg549 (pcOf 549) 3
sym_block blk551 := symRun { noAlias := true } seg551 (pcOf 551) 10
sym_block blk560 := symRun { noAlias := true } seg560 (pcOf 560) 6
sym_block blk565 := symRun { noAlias := true } seg565 (pcOf 565) 3
sym_block blk567 := symRun { noAlias := true } seg567 (pcOf 567) 2
sym_block blk568 := symRun { noAlias := true } seg568 (pcOf 568) 20
sym_block blk587 := symRun { noAlias := true } seg587 (pcOf 587) 17
sym_block blk603 := symRun { noAlias := true } seg603 (pcOf 603) 3
sym_block blk605 := symRun { noAlias := true } seg605 (pcOf 605) 3
sym_block blk607 := symRun { noAlias := true } seg607 (pcOf 607) 8

end SigGolfCandidate.Sign
