import SigGolfCandidate.Hypertree.Images

namespace SigGolfCandidate.Hypertree
open SigGolf

set_option maxRecDepth 4096 in
/-- Static admission for the exact generated bytecode, not a security certificate. -/
theorem admitted : submission.Admissible := by
  constructor
  · change 1 ≤ signatureBytes ∧ signatureBytes ≤ MAX_WITNESS_BYTES
    decide
  · intro phase
    cases phase <;> decide

/-- A position-tweaked chain, with no assumptions on the hash function. -/
def walk {α : Type} (hash : Nat → α → α) (start : Nat) : Nat → α → α
  | 0, value => value
  | count + 1, value => walk hash (start + 1) count (hash start value)

theorem walk_append {α : Type} (hash : Nat → α → α) (start first rest : Nat) (value : α) :
    walk hash start (first + rest) value =
      walk hash (start + first) rest (walk hash start first value) := by
  induction first generalizing start value with
  | zero => simp [walk]
  | succ first ih =>
    simpa [walk, Nat.succ_add, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
      ih (start + 1) (hash start value)

/-- Every Winternitz chain fragment recovers its endpoint, for every oracle. The bytecode refinement is a separate obligation. -/
theorem recover_chain {α : Type} (hash : Nat → α → α) (secret : α) (digit : Fin 8) :
    walk hash digit.val (7 - digit.val) (walk hash 0 digit.val secret) = walk hash 0 7 secret := by
  have hd : digit.val ≤ 7 := by omega
  simpa [Nat.add_sub_of_le hd] using (walk_append hash 0 digit.val (7 - digit.val) secret).symm

/-- Compression-count arithmetic for the reference algorithm. CandidateFields assembles the bytecode resource proofs; Certificate supplies the complete competition claim. -/
def referenceKeygenCompressions : Nat := 2 * (46 * (1 + 7) + 12) + 1
def referenceSignCompressions : Nat := 2 + 2 + 5 + 159 * referenceKeygenCompressions
def referenceVerificationCompressions : Nat := 2 + 2 + 159 * (46 * 7 + 12 + 1)

theorem reference_keygen_budget : referenceKeygenCompressions ≤ BUDGET_KEYGEN := by decide
theorem reference_sign_budget : referenceSignCompressions ≤ BUDGET_SIGN := by decide
theorem reference_sign_count : referenceSignCompressions = 121008 := by decide
theorem reference_verify_count : referenceVerificationCompressions = 53269 := by decide
theorem signature_size : signatureBytes = 119632 := rfl

/-- info: 'SigGolfCandidate.Hypertree.admitted' depends on axioms: [propext] -/
#guard_msgs in
#print axioms admitted

/-- info: 'SigGolfCandidate.Hypertree.recover_chain' depends on axioms: [propext, Quot.sound] -/
#guard_msgs in
#print axioms recover_chain

end SigGolfCandidate.Hypertree
