import SigGolfCandidate.Hypertree.SecurityMonitorGraphView
import SigGolfCandidate.Hypertree.SecurityNonceProgram

namespace SigGolfCandidate.Hypertree.SecurityMonitorNonceLift
open SigGolf OracleComp OracleSpec Reference SecurityGraphPassive SecurityGraphFactor
  SecurityGraphMonitorProgram
set_option backward.isDefEq.respectTransparency false
set_option maxRecDepth 4096

abbrev NP := SecurityNonceProgram.Program
abbrev NO := SecurityNonceProgram.Outcome

/-- Translate a graph operation with its full passive outcome retained. The
fixed graph table is independent of the nonce table; no nonce is read here. -/
noncomputable def liftGraph {α β : Type} (points : PointTable) :
    QueryCache PointSpec → Program α → (Outcome α → NP β) → NP β
  | _, .done value, next => next ⟨value, false, 0⟩
  | cache, .reveal point continuation, next =>
      liftGraph points (cache.cacheQuery point (points point)) (continuation (points point)) next
  | cache, .guess point value continuation, next =>
      liftGraph points cache continuation (fun result =>
        next (addTest (decide (cache point = none ∧ truncate (points point) = value)) result))
  | cache, .coin n continuation, next => .coin n (fun answer =>
      liftGraph points cache (continuation answer) next)
  | cache, .bits continuation, next => .bits (fun answer =>
      liftGraph points cache (continuation answer) next)
  | cache, .collision target continuation, next => .bits (fun answer =>
      liftGraph points cache (continuation answer) (fun result =>
        next (addTest (decide (truncate answer = target)) result)))

/-- Exact joint law, including any nonce flags/counters generated by the
continuation and all graph flags/counters passed to it. -/
theorem run_liftGraph {α β : Type} (points : PointTable) (nonces : NonceTable)
    (exposed : QueryCache PointSpec) (nonceCache : SecurityNonceMonitor.NonceCache)
    (program : Program α) (next : Outcome α → NP β) :
    SecurityNonceProgram.run nonces nonceCache (liftGraph points exposed program next) =
      (run points exposed program >>= fun result => SecurityNonceProgram.run nonces nonceCache (next result)) := by
  induction program generalizing exposed next with
  | done value => simp only [liftGraph, run, pure_bind]
  | reveal point continuation ih => exact ih (points point) _ _
  | guess point value continuation ih =>
    simp only [liftGraph, run, bind_map_left]
    exact ih exposed _
  | coin n continuation ih | bits continuation ih =>
    simp only [liftGraph, run, SecurityNonceProgram.run, bind_assoc]
    apply bind_congr
    intro answer
    exact ih answer exposed _
  | collision target continuation ih =>
    simp only [liftGraph, run, SecurityNonceProgram.run, bind_assoc, bind_map_left]
    apply bind_congr
    intro answer
    exact ih answer exposed _

/-- Map only the retained value, leaving the passive nonce state untouched. -/
def map {α β : Type} (f : α → β) : NP α → NP β
  | .pure value => .pure (f value)
  | .reveal message next => .reveal message (fun answer => map f (next answer))
  | .guess message nonce next => .guess message nonce (map f next)
  | .coin n next => .coin n (fun answer => map f (next answer))
  | .bits next => .bits (fun answer => map f (next answer))

def mapOutcome {α β : Type} (f : α → β) (result : NO α) : NO β :=
  ⟨f result.value, result.bad, result.guesses⟩

theorem run_map {α β : Type} (f : α → β) (table : NonceTable)
    (cache : SecurityNonceMonitor.NonceCache) (program : NP α) :
    SecurityNonceProgram.run table cache (map f program) =
      mapOutcome f <$> SecurityNonceProgram.run table cache program := by
  induction program generalizing cache with
  | pure value => rfl
  | reveal message next ih => exact ih (table message) _
  | guess message nonce next ih =>
    simp only [map, SecurityNonceProgram.run, ih, Functor.map_map]
    rfl
  | coin n next ih | bits next ih =>
    simp only [map, SecurityNonceProgram.run, ih, map_bind]

/-- Lift a graph macro while retaining its ordinary result. Nonce annotations
remain separate, and the full public history is part of the retained result. -/
noncomputable def liftValue {α β : Type} (points : PointTable) (exposed : QueryCache PointSpec)
    (program : Program α) (next : α → NP β) : NP β :=
  liftGraph points exposed program (fun result => next result.value)

noncomputable def observe {α : Type} (nonces : NonceTable)
    (cache : SecurityNonceMonitor.NonceCache) (program : NP α) : ProbComp α :=
  SecurityNonceProgram.Outcome.value <$> SecurityNonceProgram.run nonces cache program

theorem run_liftValue {α β : Type} (points : PointTable) (nonces : NonceTable)
    (exposed : QueryCache PointSpec) (nonceCache : SecurityNonceMonitor.NonceCache)
    (program : Program α) (next : α → NP β) :
    SecurityNonceProgram.run nonces nonceCache (liftValue points exposed program next) =
      (Outcome.value <$> run points exposed program >>= fun value =>
        SecurityNonceProgram.run nonces nonceCache (next value)) := by
  rw [liftValue, run_liftGraph, bind_map_left]

theorem observe_liftValue {α β : Type} (points : PointTable) (nonces : NonceTable)
    (exposed : QueryCache PointSpec) (nonceCache : SecurityNonceMonitor.NonceCache)
    (program : Program α) (next : α → NP β) :
    observe nonces nonceCache (liftValue points exposed program next) =
      (Outcome.value <$> run points exposed program >>= fun value => observe nonces nonceCache (next value)) := by
  rw [observe, run_liftValue, map_bind]
  rfl

end SigGolfCandidate.Hypertree.SecurityMonitorNonceLift
