import SigGolfCandidate.Images

/-!
# The sig.golf submission (SPHINCS-golf, witness mode `perm`)

Sizes `S = W = 7080`, the shared layout of `PROGRAMS.md` (message `0x40`, secret key `0x80`,
public key `0xA0`, cache `0x44A0`, signature `0x2650`, witness `0x800`) and the four images
generated by `work/py/gen.py` (`SigGolfCandidate/Images.lean`).
-/

namespace SigGolfCandidate
open SigGolf

/-- The submission value. -/
def submission : Submission where
  sizes := ⟨7080, 7080⟩
  layout := ⟨0x40, 0x80, 0xA0, 0x44A0, 0x2650, 0x800⟩
  image
    | .keygen => Images.keygenImage
    | .sign => Images.signImage
    | .expand => Images.expandImage
    | .verify => Images.verifyImage

theorem submission_eq_images : submission = Images.submission := by
  unfold submission Images.submission; rfl

theorem submission_sizes : submission.sizes = ⟨7080, 7080⟩ := rfl

/-! ### Admission, image by image

Deciding `Image.Valid` outright makes the kernel run `List.append` over the concatenated code
chunks (20 046 words for `verify`), which peaks near 10 GB. Instead the code list is rewritten to its
chunks, `List.length_append` splits the length, and the kernel only counts each chunk. The equation
for the code list is obtained by `delta` inside an equation (a plain `unfold` would generate an
equation lemma whose elaboration evaluates the list), and every step is a rewrite, so no
definitional check ever reduces closed arithmetic over the full length. The layout half only reads
the (empty) data section and is decided directly. -/

/-- Proves `(submission.image phase).Valid submission.sizes submission.layout` for an image whose
code list is `code`, a concatenation of chunks. -/
local macro "image_valid " code:ident : tactic => `(tactic| (
  have hcode : $code = $code := rfl
  conv at hcode => rhs; delta $code:ident
  rw [Riscv.Image.Valid]
  refine ⟨?_, by decide +kernel⟩
  rw [Riscv.Image.byteSize, show Riscv.Image.code _ = $code from rfl, hcode]
  try simp only [List.length_append]
  decide +kernel))

theorem submission_keygen_valid :
    (submission.image .keygen).Valid submission.sizes submission.layout := by
  image_valid Images.keygenCode

theorem submission_sign_valid :
    (submission.image .sign).Valid submission.sizes submission.layout := by
  image_valid Images.signCode

theorem submission_expand_valid :
    (submission.image .expand).Valid submission.sizes submission.layout := by
  image_valid Images.expandCode

set_option maxRecDepth 200000 in
theorem submission_verify_valid :
    (submission.image .verify).Valid submission.sizes submission.layout := by
  image_valid Images.verifyCode

/-- Static admission (sizes, image-size limits, aligned nonoverlapping buffers). -/
theorem submission_admissible : submission.Admissible := by
  refine ⟨by unfold Sizes.Valid; decide, ?_⟩
  intro phase
  cases phase
  · exact submission_keygen_valid
  · exact submission_sign_valid
  · exact submission_expand_valid
  · exact submission_verify_valid

end SigGolfCandidate

