-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.
import SigGolfCandidate.Sign.PackStep

namespace SigGolfCandidate.Sign
open SigGolf SigGolf.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 0: instructions 639 .. 1077, signature dwords 0 .. 79. -/

set_option maxRecDepth 100000

sym_block blk639 := symRun { noAlias := true } seg639 (pcOf 639) 440

kernel_theorem blk639_pc : ∀ t : MachineState, (blk639.res.toState t).pc = pcOf 1078
kernel_theorem blk639_addrs : ∀ t : MachineState, blk639.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 0 + 8 * i))).reverse
kernel_theorem blk639_words : ∀ t : MachineState,
    (blk639.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 0)) 80 =
      ((packTab.drop 0).take 80).map (packDW t)

theorem packStep_639 : PackStep 639 1078 0 80 439 :=
  packStep_of blk639 codeAt_639 rfl blk639_pc rfl rfl blk639_words blk639_addrs (by norm_num)

end SigGolfCandidate.Sign
