import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (34, 42, 61, 88, 101) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00500493, 0x000349b7, 0x10098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x2011ee93, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13]
def seg_23 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_30 : List (BitVec 32) := [0x6b502223, 0x6a000513, 0x04000593, 0x0e000613]
def seg_34 : List (BitVec 32) := [0x00000073]
def seg_35 : List (BitVec 32) := [0x0e003823, 0x0e003c23, 0x00000b93]
def seg_38 : List (BitVec 32) := [0x001b8b93, 0x0d802223, 0x0c000513, 0x0e000613]
def seg_42 : List (BitVec 32) := [0x00000073]
def seg_43 : List (BitVec 32) := [0x0e003823, 0x0e003c23, 0x001c0c13, 0x00700193, 0xfc3b9ee3]
def seg_48 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0e003083, 0x0e803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xf83a9ce3]
def seg_57 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_61 : List (BitVec 32) := [0x00000073]
def seg_62 : List (BitVec 32) := [0x001a0a13, 0xf71a10e3]
def seg_64 : List (BitVec 32) := [0x00100793]
def seg_65 : List (BitVec 32) := [0x02079193, 0x01041e93, 0x01d1e1b3, 0x3011e193, 0x1c303023, 0x1de02423, 0x0018d893, 0x00000813]
def seg_73 : List (BitVec 32) := [0x1d002623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x00398633]
def seg_88 : List (BitVec 32) := [0x00000073]
def seg_89 : List (BitVec 32) := [0x00180813, 0xfb181ee3]
def seg_91 : List (BitVec 32) := [0x00178793, 0xf8f4dae3]
def seg_93 : List (BitVec 32) := [0x000349b7, 0x10098993, 0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x00100293, 0x00000513]
def seg_101 : List (BitVec 32) := [0x00000073]

def L : Rv.Layout := [(0, seg_0), (23, seg_23), (30, seg_30), (34, seg_34), (35, seg_35), (38, seg_38), (42, seg_42), (43, seg_43), (48, seg_48), (57, seg_57), (61, seg_61), (62, seg_62), (64, seg_64), (65, seg_65), (73, seg_73), (88, seg_88), (89, seg_89), (91, seg_91), (93, seg_93), (101, seg_101)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_23 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 23)) seg_23 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_30 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 30)) seg_30 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_34 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 34)) seg_34 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_35 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 35)) seg_35 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_38 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 38)) seg_38 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_42 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 42)) seg_42 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_43 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 43)) seg_43 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_48 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 48)) seg_48 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 57)) seg_57 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_61 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 61)) seg_61 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_62 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 62)) seg_62 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_64 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 64)) seg_64 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_65 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 65)) seg_65 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_73 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 73)) seg_73 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_88 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 88)) seg_88 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_89 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 89)) seg_89 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_91 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 91)) seg_91 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_93 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 93)) seg_93 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_101 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 101)) seg_101 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)

sym_block blk_0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 100
sym_block blk_23 := symRun { noAlias := true } seg_23 (BitVec.ofNat 64 (0x1000 + 4 * 23)) 100
sym_block blk_30 := symRun { noAlias := true } seg_30 (BitVec.ofNat 64 (0x1000 + 4 * 30)) 100
sym_block blk_35 := symRun { noAlias := true } seg_35 (BitVec.ofNat 64 (0x1000 + 4 * 35)) 100
sym_block blk_38 := symRun { noAlias := true } seg_38 (BitVec.ofNat 64 (0x1000 + 4 * 38)) 100
sym_block blk_43 := symRun { noAlias := true } seg_43 (BitVec.ofNat 64 (0x1000 + 4 * 43)) 100
sym_block blk_48 := symRun { noAlias := true } seg_48 (BitVec.ofNat 64 (0x1000 + 4 * 48)) 100
sym_block blk_57 := symRun { noAlias := true } seg_57 (BitVec.ofNat 64 (0x1000 + 4 * 57)) 100
sym_block blk_62 := symRun { noAlias := true } seg_62 (BitVec.ofNat 64 (0x1000 + 4 * 62)) 100
sym_block blk_64 := symRun { noAlias := true } seg_64 (BitVec.ofNat 64 (0x1000 + 4 * 64)) 100
sym_block blk_65 := symRun { noAlias := true } seg_65 (BitVec.ofNat 64 (0x1000 + 4 * 65)) 100
sym_block blk_73 := symRun { noAlias := true } seg_73 (BitVec.ofNat 64 (0x1000 + 4 * 73)) 100
sym_block blk_89 := symRun { noAlias := true } seg_89 (BitVec.ofNat 64 (0x1000 + 4 * 89)) 100
sym_block blk_91 := symRun { noAlias := true } seg_91 (BitVec.ofNat 64 (0x1000 + 4 * 91)) 100
sym_block blk_93 := symRun { noAlias := true } seg_93 (BitVec.ofNat 64 (0x1000 + 4 * 93)) 100

end SigGolfCandidate.Keygen
