import SigGolfCandidate.Expand.Mem
import SigGolfCandidate.Submission

/-!
# `keygen`: segment table and symbolic blocks (generated by `gen_keygen.py`)

`seg_a_b` is instructions `a .. b-1`; `blk_a` its symbolic run (`noAlias`), `codeAt_a` its
placement. The `ecall`s (39, 52, 69, 98, 129, 168, 171) are singleton segments.
-/

namespace SigGolfCandidate.Keygen
open RiscvZkvm.Rv64 SigGolf SigGolf.Riscv SigGolfCandidate.Rv

set_option maxRecDepth 8192

def seg_0 : List (BitVec 32) := [0x08003083, 0x6c103023, 0x08803083, 0x6c103423, 0x09003083, 0x6c103823, 0x09803083, 0x6c103c23, 0x00000413, 0x00000f13, 0x00b00493, 0x000049b7, 0x4c098993, 0x01041193, 0x0011ee93, 0x6bd02023, 0x1011ee93, 0x0dd02023, 0x2011ee93, 0x35d03023, 0x00100193, 0x009198b3, 0x00000a13, 0x0e003023, 0x0e003423]
def seg_25 : List (BitVec 32) := [0x020a1193, 0x01e1e1b3, 0x6a303423, 0x0c303423, 0x34303423, 0x00000a93, 0x00000c13]
def seg_32 : List (BitVec 32) := [0x001af193, 0x00019e63]
def seg_34 : List (BitVec 32) := [0x001ad193, 0x6a302223, 0x6a000513, 0x04000593, 0x14000613]
def seg_39 : List (BitVec 32) := [0x00000073]
def seg_40 : List (BitVec 32) := [0x001af193, 0x00419193, 0x1401b083, 0x1481b103, 0x0e103823, 0x0e203c23, 0x0c000513, 0x0f000613, 0x00000b93]
def seg_49 : List (BitVec 32) := [0x001b8b93, 0x0d802223, 0x0c000513]
def seg_52 : List (BitVec 32) := [0x00000073]
def seg_53 : List (BitVec 32) := [0x001c0c13, 0x00700193, 0xfe3b94e3]
def seg_56 : List (BitVec 32) := [0x001c0c13, 0x004a9193, 0x0f003083, 0x0f803103, 0x3611b023, 0x3621b423, 0x001a8a93, 0x02a00193, 0xf83a90e3]
def seg_65 : List (BitVec 32) := [0x34000513, 0x2c000593, 0x004a1193, 0x00398633]
def seg_69 : List (BitVec 32) := [0x00000073]
def seg_70 : List (BitVec 32) := [0x001a0a13, 0xf51a14e3]
def seg_72 : List (BitVec 32) := [0x00100793]
def seg_73 : List (BitVec 32) := [0x02079193, 0x01041e93, 0x01d1e1b3, 0x3011e193, 0x1c303023, 0x1de02423, 0x00489193, 0x00398cb3, 0x0018d893, 0x00000813]
def seg_83 : List (BitVec 32) := [0x1d002623, 0x00581193, 0x013181b3, 0x0001b083, 0x1e103023, 0x0081b083, 0x1e103423, 0x0101b083, 0x1e103823, 0x0181b083, 0x1e103c23, 0x1c000513, 0x04000593, 0x00481193, 0x003c8633]
def seg_98 : List (BitVec 32) := [0x00000073]
def seg_99 : List (BitVec 32) := [0x00180813, 0xfb181ee3]
def seg_101 : List (BitVec 32) := [0x000c8993, 0x00178793, 0xf8f4d4e3]
def seg_104 : List (BitVec 32) := [0x0009b083, 0x0089b103, 0x0a103023, 0x0a203423, 0x0009b023, 0x0009b423, 0x0009b823, 0x0009bc23]
def seg_112 : List (BitVec 32) := [0x00004a37, 0x4c0a0a13, 0x00000793]
def seg_115 : List (BitVec 32) := [0x00100193, 0x00b00e93, 0x40fe8eb3, 0x01d198b3, 0x00000813]
def seg_120 : List (BitVec 32) := [0x02079193, 0x68118193, 0x68018193, 0x6a303023, 0x02081193, 0x6a303423, 0x6a000513, 0x04000593, 0x14000613]
def seg_129 : List (BitVec 32) := [0x00000073]
def seg_130 : List (BitVec 32) := [0x000a3083, 0x14003103, 0x0020c0b3, 0x001a3023, 0x008a3083, 0x14803103, 0x0020c0b3, 0x001a3423, 0x010a0a13, 0x00180813, 0xfb1818e3]
def seg_141 : List (BitVec 32) := [0x00178793, 0x00b00193, 0xf83798e3]
def seg_144 : List (BitVec 32) := [0x00004eb7, 0x4a0e8e93, 0x000011b7, 0xe0118193, 0xfe3eb023, 0x08003083, 0x001eb023, 0x08803083, 0x001eb423, 0x09003083, 0x001eb823, 0x09803083, 0x001ebc23, 0x000141b7, 0x4a018193, 0x0001b023, 0x0001b423, 0x0001b823, 0x0001bc23, 0xfe0e8513, 0x000105b7, 0x04058593, 0x00004637, 0x4a060613]
def seg_168 : List (BitVec 32) := [0x00000073]
def seg_169 : List (BitVec 32) := [0x00100293, 0x00000513]
def seg_171 : List (BitVec 32) := [0x00000073]

def L : Rv.Layout := [(0, seg_0), (25, seg_25), (32, seg_32), (34, seg_34), (39, seg_39), (40, seg_40), (49, seg_49), (52, seg_52), (53, seg_53), (56, seg_56), (65, seg_65), (69, seg_69), (70, seg_70), (72, seg_72), (73, seg_73), (83, seg_83), (98, seg_98), (99, seg_99), (101, seg_101), (104, seg_104), (112, seg_112), (115, seg_115), (120, seg_120), (129, seg_129), (130, seg_130), (141, seg_141), (144, seg_144), (168, seg_168), (169, seg_169), (171, seg_171)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The keygen image. -/
abbrev image : Image := submission.image .keygen

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 0)) seg_0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 25)) seg_25 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_32 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 32)) seg_32 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_34 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 34)) seg_34 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_39 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 39)) seg_39 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_40 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 40)) seg_40 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_49 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 49)) seg_49 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_52 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 52)) seg_52 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_53 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 53)) seg_53 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_56 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 56)) seg_56 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_65 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 65)) seg_65 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_69 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 69)) seg_69 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 70)) seg_70 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_72 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 72)) seg_72 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_73 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 73)) seg_73 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_83 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 83)) seg_83 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_98 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 98)) seg_98 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_99 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 99)) seg_99 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_101 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 101)) seg_101 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 104)) seg_104 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_112 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 112)) seg_112 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_115 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 115)) seg_115 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_120 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 120)) seg_120 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_129 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 129)) seg_129 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_130 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 130)) seg_130 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_141 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 141)) seg_141 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_144 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 144)) seg_144 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_168 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 168)) seg_168 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_169 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 169)) seg_169 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_171 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 171)) seg_171 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)

sym_block blk_0 := symRun { noAlias := true } seg_0 (BitVec.ofNat 64 (0x1000 + 4 * 0)) 100
sym_block blk_25 := symRun { noAlias := true } seg_25 (BitVec.ofNat 64 (0x1000 + 4 * 25)) 100
sym_block blk_32 := symRun { noAlias := true } seg_32 (BitVec.ofNat 64 (0x1000 + 4 * 32)) 100
sym_block blk_34 := symRun { noAlias := true } seg_34 (BitVec.ofNat 64 (0x1000 + 4 * 34)) 100
sym_block blk_40 := symRun { noAlias := true } seg_40 (BitVec.ofNat 64 (0x1000 + 4 * 40)) 100
sym_block blk_49 := symRun { noAlias := true } seg_49 (BitVec.ofNat 64 (0x1000 + 4 * 49)) 100
sym_block blk_53 := symRun { noAlias := true } seg_53 (BitVec.ofNat 64 (0x1000 + 4 * 53)) 100
sym_block blk_56 := symRun { noAlias := true } seg_56 (BitVec.ofNat 64 (0x1000 + 4 * 56)) 100
sym_block blk_65 := symRun { noAlias := true } seg_65 (BitVec.ofNat 64 (0x1000 + 4 * 65)) 100
sym_block blk_70 := symRun { noAlias := true } seg_70 (BitVec.ofNat 64 (0x1000 + 4 * 70)) 100
sym_block blk_72 := symRun { noAlias := true } seg_72 (BitVec.ofNat 64 (0x1000 + 4 * 72)) 100
sym_block blk_73 := symRun { noAlias := true } seg_73 (BitVec.ofNat 64 (0x1000 + 4 * 73)) 100
sym_block blk_83 := symRun { noAlias := true } seg_83 (BitVec.ofNat 64 (0x1000 + 4 * 83)) 100
sym_block blk_99 := symRun { noAlias := true } seg_99 (BitVec.ofNat 64 (0x1000 + 4 * 99)) 100
sym_block blk_101 := symRun { noAlias := true } seg_101 (BitVec.ofNat 64 (0x1000 + 4 * 101)) 100
sym_block blk_104 := symRun { noAlias := true } seg_104 (BitVec.ofNat 64 (0x1000 + 4 * 104)) 100
sym_block blk_112 := symRun { noAlias := true } seg_112 (BitVec.ofNat 64 (0x1000 + 4 * 112)) 100
sym_block blk_115 := symRun { noAlias := true } seg_115 (BitVec.ofNat 64 (0x1000 + 4 * 115)) 100
sym_block blk_120 := symRun { noAlias := true } seg_120 (BitVec.ofNat 64 (0x1000 + 4 * 120)) 100
sym_block blk_130 := symRun { noAlias := true } seg_130 (BitVec.ofNat 64 (0x1000 + 4 * 130)) 100
sym_block blk_141 := symRun { noAlias := true } seg_141 (BitVec.ofNat 64 (0x1000 + 4 * 141)) 100
sym_block blk_144 := symRun { noAlias := true } seg_144 (BitVec.ofNat 64 (0x1000 + 4 * 144)) 100
sym_block blk_169 := symRun { noAlias := true } seg_169 (BitVec.ofNat 64 (0x1000 + 4 * 169)) 100

end SigGolfCandidate.Keygen
